Repository loculus-project/loculus, pull requests merged in 2024-12, with the labels that each got.

#3279 fix(backend,website): calculate status counts efficiently & request only aggregates for submission portal
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  website/src/components/ReviewPage/ReviewPage.tsx
  website/src/hooks/useSubmissionOperations.ts
  website/src/pages/[organism]/submission/[groupId]/index.astro
  website/src/services/backendApi.ts
  website/src/types/backend.ts
Labels: preview, review please

#3263 feat(preprocessing): parse dates into date ranges to correctly represent incomplete dates
  docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
  kubernetes/loculus/values.yaml
  preprocessing/nextclade/environment.yml
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/tests/test_processing_functions.py
Labels: preview, review please

#3329 fix(website): line up organism cards with other UI elements
  website/src/components/IndexPage/OrganismCard.astro
  website/src/pages/index.astro
Labels: preview

#3342 fix(website): Adjust break all to break word
  website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx
  website/src/styles/base.scss
Labels: preview, format_me

#3308 feat(website): Adapt collectionDate search to work with date ranges
  docs/public/images/strict_not_strict.drawio.svg
  docs/src/content/docs/for-users/search-sequences.md
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/components/ReviewPage/ReviewCard.tsx
  website/src/components/SearchPage/SearchForm.spec.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/fields/AccessionField.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.spec.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.tsx
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/SearchPage/fields/DateRangeField.spec.tsx
  website/src/components/SearchPage/fields/DateRangeField.tsx
  website/src/components/SearchPage/fields/NormalTextField.tsx
  website/src/types/config.ts
  website/src/utils/CustomTooltip.tsx
  website/src/utils/search.ts
Labels: preview

#3350 fix(website): work around astro bug executing middleware at build time
  website/src/config.ts
  website/src/middleware.ts
Labels: preview

#3353 feat(website): specify width for column(s) in search table
  docs/src/content/docs/for-administrators/setup-with-kubernetes.md
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/Table.tsx
  website/src/types/config.ts
Labels: preview, format_me

#3356 fix(backend): reset etag for data_use_terms_table updates
  backend/docs/db/schema.sql
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/main/resources/db/migration/V1.7__add_table_update_trigger_for_data_use_terms.sql
Labels: preview, update_db_schema

#3327 feat(deposition): Use github pages to not get rate limited, assert sequences with ena specific fields were submitted by us or the insdc_submission_group
  ena-submission/config/defaults.yaml
  ena-submission/scripts/get_ena_submission_list.py
  ena-submission/src/ena_deposition/config.py
Labels: preview

#3361 chore(kubernetes): upgrade to LAPIS 0.3.10
  kubernetes/loculus/values.yaml
Labels: preview, deployment

#3355 chore(kubernetes): migrate away from deprecated env variable names
  kubernetes/loculus/templates/keycloak-deployment.yaml
Labels: preview

#3073 fix(backend): lock rows that are being streamed to pipeline
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
Labels: format_me

#3381 fix(backend): use correct syntax to extend async timeout
  backend/src/main/resources/application.properties
Labels: preview

#3385 fix(website): don't allow search page to expand beyond window width - instead make the table scroll
  .gitignore
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/Table.tsx
Labels: preview

#3396 perf(silo-prepro): speed up by using more efficient jq command
  kubernetes/loculus/silo_import_job.sh
Labels: preview

#3402 fix(prepro): don't crash when backend sends error instead of valid ndjson
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
Labels: preview

#3409 feat(website): Limit organism card container width when there are 5 organisms
  website/src/pages/index.astro
Labels: preview, format_me

#3417 chore(website): center organism cards
  website/src/pages/index.astro
Labels: preview

#3419 fix(website): Set min width to 130px for columns without defined widths
  website/src/components/SearchPage/Table.tsx
Labels: preview

#3397 style: Trying out a new active-filter style
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx
  website/src/components/SearchPage/DownloadDialog/OptionBlock.tsx
  website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/common/ActiveFilters.spec.tsx
  website/src/components/common/ActiveFilters.tsx
  website/src/utils/search.ts
Labels: preview

#3376 chore(deps): Upgrade to astro v5
  website/package-lock.json
  website/package.json
  website/tsconfig.json
Labels: website, dependencies, preview

#3380 feat: earliest release date
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/config/Config.kt
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/main/kotlin/org/loculus/backend/utils/EarliestReleaseDateFinder.kt
  backend/src/test/kotlin/org/loculus/backend/config/BackendSpringConfigTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/utils/EarliestReleaseDateFinderTest.kt
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
Labels: preview

#3421 feat(ingest): Improve memory usage
  ingest/scripts/filter_out_depositions.py
  ingest/scripts/format_ncbi_metadata.py
  ingest/scripts/prepare_metadata.py
Labels: preview

#3348 feat(website, backend, prepro)!: Update error schema with input and output metadata field names
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/resources/db/migration/V1.8__update_error_schema.sql
  backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt
  preprocessing/dummy/main.py
  preprocessing/nextclade/src/loculus_preprocessing/datatypes.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py
  preprocessing/nextclade/tests/factory_methods.py
  preprocessing/nextclade/tests/test_config.yaml
  preprocessing/nextclade/tests/test_processing_functions.py
  preprocessing/specification.md
  website/src/components/Edit/DataRow.tsx
  website/src/components/Edit/EditPage.spec.tsx
  website/src/components/Edit/EditPage.tsx
  website/src/components/ReviewPage/ReviewCard.tsx
  website/src/types/backend.ts
  website/tests/util/preprocessingPipeline.ts
  website/vitest.setup.ts
Labels: preview

#3433 feat(backend): Return `pipelineVersion` in `get-released-data`
  backend/docs/db/schema.sql
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SequenceEntriesView.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/resources/db/migration/V1.9__update_sequence_entries_view_add_pipeline_version.sql
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/utils/EarliestReleaseDateFinderTest.kt
  kubernetes/loculus/templates/_common-metadata.tpl
Labels: backend, preview, update_db_schema

#3425 feat(website): Make submission template configurable
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/config.ts
  website/src/pages/[organism]/submission/template/index.ts
  website/src/types/config.ts
  website/tests/pages/revise/revise.page.ts
  website/tests/pages/submission/template.spec.ts
Labels: preview

#3434 feat: Add lineage definition file to SILO import config
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/silo_import_job.sh
  kubernetes/loculus/templates/_lineage-system-for-organism.tpl
  kubernetes/loculus/templates/_siloDatabaseConfig.tpl
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
  kubernetes/loculus/values.yaml
  preprocessing/dummy/lineage.yaml
  preprocessing/dummy/main.py
  website/tests/pages/search/index.spec.ts
  website/tests/util/preprocessingPipeline.ts
Labels: preview

#3429 feat(ingest): Add option to use nextclade sort to identify segments for multi-segmented organisms
  ingest/Snakefile
  ingest/environment.yml
  ingest/scripts/call_loculus.py
  ingest/scripts/parse_nextclade_sort_output.py
  ingest/scripts/prepare_metadata.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
Labels: preview

#3359 feat(website): show API URLs on API documentation page
  website/src/pages/api-documentation/index.astro
  website/src/utils/getAuthUrl.ts
Labels: preview
