Repository loculus-project/loculus, pull requests merged in 2024-10, with the labels that each got.

#2914 fix(website): don't display data as "restricted" when the last restricted data use terms expired
  website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
Labels: bug, website, preview, format_me

#2909 feat(deployment): Add basic-auth to keycloak
  kubernetes/loculus/templates/ena-submission-config.yaml
  kubernetes/loculus/templates/ingest-config.yaml
  kubernetes/loculus/templates/ingressroute.yaml
  kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
Labels: preview

#2908 fix(ingest): Change to ingest/ena-submission to debug log level
  ena-submission/config/defaults.yaml
  ingest/config/defaults.yaml
Labels: preview

#2929 fix(deployment): Use recreate strategy for stand in dbs
  kubernetes/loculus/templates/keycloak-database-deployment.yaml
  kubernetes/loculus/templates/loculus-database-standin.yaml
Labels: preview

#2938 chore(website): add playwright outputs to astro check exclude dir
  website/tsconfig.json
Labels: website, preview

#2900 fix(ena-submission): fix ena request error handling
  ena-submission/scripts/call_loculus.py
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/create_sample.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/notifications.py
  ena-submission/scripts/trigger_submission_to_ena.py
  ena-submission/scripts/upload_external_metadata_to_loculus.py
  kubernetes/loculus/templates/ena-submission-deployment.yaml
Labels: preview

#2946 fix(ena-submission): temporarily do not send gcaAccession to Loculus
  ena-submission/scripts/deposition_dry_run.py
  ena-submission/scripts/upload_external_metadata_to_loculus.py
Labels: preview

#2947 feat(deposition): submit EMBL flatfile instead of fasta for better nucleotide metadata
  ena-submission/ENA_submission.md
  ena-submission/environment.yml
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/ena_types.py
  ena-submission/scripts/test_ena_submission.py
  kubernetes/loculus/values.yaml
Labels: preview

#2959 feat(backend): audit log when someone sets data use terms
  backend/src/main/kotlin/org/loculus/backend/service/datauseterms/DataUseTermsDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt
Labels: backend

#2916 [BREAKING] Don't include submission id in website `input fields`, add accession to metadata revision template
  kubernetes/loculus/values.yaml
  website/README.md
  website/src/components/Edit/EditPage.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/pages/[organism]/submission/template/index.ts
  website/src/routes/routes.ts
  website/src/settings.ts
  website/tests/pages/submission/submit.page.ts
  website/tests/pages/submission/template.spec.ts
Labels: website, preview, deployment

#2934 chore: update to LAPIS 0.3.4, SILO 0.2.22
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
Labels: preview, deployment

#2965 Ena add address
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/test_ena_submission.py
Labels: preview

#2960 feat(deposition): improvements and fixes
  ena-submission/.gitignore
  ena-submission/config/config.yaml
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/create_sample.py
  ena-submission/scripts/deposition_dry_run.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/ena_types.py
  ena-submission/scripts/test_ena_submission.py
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/ena-submission-config.yaml
  kubernetes/loculus/values.yaml
Labels: preview, needs-ppx-values-pr

#2971 feat(prepro): Add metadata processing tests
  .github/workflows/preprocessing-tests.yaml
  kubernetes/loculus/values.yaml
  preprocessing/nextclade/.dockerignore
  preprocessing/nextclade/README.md
  preprocessing/nextclade/pyproject.toml
  preprocessing/nextclade/src/loculus_preprocessing/config.py
  preprocessing/nextclade/src/loculus_preprocessing/datatypes.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/testdata/metadata.tsv
  preprocessing/nextclade/testdata/sequences.fasta
  preprocessing/nextclade/tests/factory_methods.py
  preprocessing/nextclade/tests/test.py
  preprocessing/nextclade/tests/test_config.yaml
  preprocessing/specification.md
Labels: preview, needs-ppx-values-pr

#2975 fix(kubernetes): don't expect `$instance.enaDeposition` config when ena submission is disabled
  kubernetes/loculus/templates/ena-submission-config.yaml
Labels: preview

#2957 docs: add reference of Helm chart configuration
  docs/src/content/docs/for-administrators/setup-with-kubernetes.md
  docs/src/content/docs/reference/helm-chart-config.mdx
Labels: preview

#2981 chore(website): don't `override` eslint rules that we set ourselves to `error`
  website/.eslintrc.cjs
Labels: website

#2988 feat(website): Add padding to code blocks in docs
  website/src/styles/mdcontainer.scss
Labels: preview

#2917 feat: Allow selecting sequences for download by checkbox
  website/src/components/SearchPage/DownloadDialog/ActiveDownloadFilters.spec.tsx
  website/src/components/SearchPage/DownloadDialog/ActiveDownloadFilters.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadButton.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadParameters.tsx
  website/src/components/SearchPage/DownloadDialog/generateDownloadUrl.ts
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/Table.tsx
Labels: preview

#2994 fix(website): show more helpful error when LAPIS returns error when fetching sequences
  website/src/services/serviceHooks.ts
Labels: website, preview

#2993 chore(kubernetes): update to LAPIS 0.3.5, SILO 0.2.23
  kubernetes/loculus/values.yaml
Labels: preview

#3011 Author formatting updates
  ena-submission/scripts/ena_submission_helper.py
  ingest/scripts/prepare_metadata.py
  ingest/tests/expected_output_cchf/metadata_post_prepare.json
  ingest/tests/test_data_cchf/metadata_post_extract.tsv
  ingest/tests/test_data_cchf/ncbi_dataset.zip
  ingest/tests/test_ingest.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/tests/test.py
  preprocessing/nextclade/tests/test_config.yaml
Labels: preview

#2990 feat(ingest): Do not use processed tsv but raw jsonl when ingesting data from NCBI Virus
  ena-submission/scripts/ena_submission_helper.py
  ingest/Snakefile
  ingest/config/defaults.yaml
  ingest/scripts/group_segments.py
  ingest/scripts/prepare_metadata.py
  ingest/scripts/rename_fields.py
  ingest/tests/expected_output_cchf/metadata_post_prepare.json
  ingest/tests/test_data_cchf/metadata_post_extract.tsv
  ingest/tests/test_data_cchf/ncbi_dataset.zip
  ingest/tests/test_ingest.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/tests/test.py
  preprocessing/nextclade/tests/test_config.yaml
Labels: preview

#3003 feat: Allow downloading metadata in the sequence detail view
  website/src/components/Navigation/OrganismSelector.astro
  website/src/components/SearchPage/SeqPreviewModal.tsx
  website/src/components/SearchPage/Table.tsx
  website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.tsx
  website/src/components/SequenceDetailsPage/SequencesBanner.astro
  website/src/components/SequenceDetailsPage/SequencesDataTableTitle.astro
  website/src/pages/seq/[accessionVersion].fa/index.ts
  website/src/pages/seq/[accessionVersion].tsv/index.ts
  website/src/pages/seq/[accessionVersion]/getSequenceDetailsTableData.ts
  website/src/pages/seq/[accessionVersion]/index.astro
  website/src/pages/seq/[accessionVersion]/versions.astro
  website/src/routes/routes.ts
  website/src/services/lapisClient.ts
  website/src/styles/base.scss
  website/src/types/lapis.ts
  website/src/utils/createDownloadAPIRoute.ts
  website/src/utils/shouldMiddlewareEnforceLogin.spec.ts
  website/tests/pages/sequences/accession.fa.spec.ts
  website/tests/pages/sequences/accession.spec.ts
  website/tests/pages/sequences/sequences.page.ts
Labels: preview

#3019 feat(website): add menu icon to download icon
  website/src/components/SearchPage/SeqPreviewModal.tsx
Labels: preview

#2982 feat(ena-deposition): Small tweaks to uploaded metadata in manifest and project
  ena-submission/.gitignore
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/deposition_dry_run.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/test_ena_submission.py
  ena-submission/test/text_project_request.xml
Labels: preview

#2980 fix(prepro): log and raise if prepro encounters config error to allow early detection
  .github/workflows/preprocessing-tests.yaml
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/tests/test.py
Labels: preprocessing, review please

#3020 fix: prevent download button layout shifts
  website/src/components/SearchPage/DownloadDialog/DowloadDialogButton.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
Labels: preview

#2976 feat(ena_deposition): Make deposition a package instead of multiple snakemake rules
  .github/workflows/ena-submission-tests.yaml
  ena-submission/Dockerfile
  ena-submission/README.md
  ena-submission/Snakefile
  ena-submission/config/defaults.yaml
  ena-submission/environment.yml
  ena-submission/pyproject.toml
  ena-submission/scripts/deposition_dry_run.py
  ena-submission/scripts/get_ena_submission_list.py
  ena-submission/scripts/test_ena_submission.py
  ena-submission/src/ena_deposition/__init__.py
  ena-submission/src/ena_deposition/__main__.py
  ena-submission/src/ena_deposition/call_loculus.py
  ena-submission/src/ena_deposition/config.py
  ena-submission/src/ena_deposition/create_assembly.py
  ena-submission/src/ena_deposition/create_project.py
  ena-submission/src/ena_deposition/create_sample.py
  ena-submission/src/ena_deposition/ena_submission_helper.py
  ena-submission/src/ena_deposition/ena_types.py
  ena-submission/src/ena_deposition/notifications.py
  ena-submission/src/ena_deposition/submission_db_helper.py
  ena-submission/src/ena_deposition/trigger_submission_to_ena.py
  ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
  kubernetes/loculus/templates/ena-submission-deployment.yaml
Labels: preview

#3032 fix(backend): allow requests to last 10hr, instead of just 30s
  backend/src/main/resources/application.properties
Labels: preview

#3039 feat(config): Add dockertag to prepro deployments to allow prepro pods to point to different commits
  kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
  preprocessing/nextclade/README.md
Labels: preview

#3044 fix(backend): get rid of logger config deprecation warnings in the log
  backend/src/main/resources/logback.xml
  backend/src/test/resources/logback-test.xml
Labels: backend, preview

#3056 chore(dependencies): bump flowbite-react and fix Datepicker
  website/package-lock.json
  website/package.json
  website/src/clientLogger.ts
  website/src/components/DataUseTerms/EditDataUseTermsButton.tsx
  website/src/components/Submission/DateChangeModal.tsx
Labels: preview

#3040 fix(config): remove unused `secrets.database.data.host` in values.yaml
  kubernetes/loculus/values.yaml
Labels: preview, deployment

#2973 Small tweaks to test-prepro-v2
  .github/workflows/preprocessing-tests.yaml
  preprocessing/nextclade/.justfile
  preprocessing/nextclade/README.md
  preprocessing/nextclade/pyproject.toml
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
  preprocessing/nextclade/src/loculus_preprocessing/config.py
  preprocessing/nextclade/src/loculus_preprocessing/datatypes.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py
  preprocessing/nextclade/tests/factory_methods.py
  preprocessing/nextclade/tests/test.py
  preprocessing/nextclade/tests/test_processing_functions.py
Labels: preview

#3077 feat(chore): Update to update to silo 0.3.0, lapis to 0.3.7, fix e2e tests
  kubernetes/loculus/values.yaml
  website/src/services/lapisApi.ts
  website/src/services/lapisClient.ts
  website/src/services/serviceHooks.ts
  website/src/types/lapis.ts
Labels: preview, format_me

#3090 fix(website): Increase website memory limit to 1024 mb to avoid crashes with very large numbers of deletions
  website/Dockerfile
Labels: preview

#3108 chore(kubernetes): silo 0.3.1
  kubernetes/loculus/values.yaml
Labels: preview

#2986 feat(prepro, ingest, deposition): Enforce author formatting in prepro, map authors accordingly in ingest and deposition
  backend/src/main/resources/db/migration/V1.4__fix_external_metadata_view.sql
  ena-submission/pyproject.toml
  ena-submission/scripts/test_ena_submission.py
  ena-submission/src/ena_deposition/create_assembly.py
  ena-submission/src/ena_deposition/ena_submission_helper.py
  ingest/Snakefile
  ingest/config/defaults.yaml
  ingest/scripts/format_ncbi_metadata.py
  ingest/scripts/group_segments.py
  ingest/scripts/prepare_metadata.py
  ingest/tests/expected_output_cchf/metadata_post_prepare.json
  ingest/tests/test_data_cchf/metadata_post_extract.tsv
  ingest/tests/test_data_cchf/ncbi_dataset.zip
  ingest/tests/test_ingest.py
  kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
  kubernetes/loculus/values.yaml
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/tests/test_config.yaml
  preprocessing/nextclade/tests/test_processing_functions.py
Labels: preview

#3063 feat(kubernetes): make public runtime config urls of the website configurable
  deploy.py
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/_lapis-urls.tpl
  kubernetes/loculus/templates/loculus-website-config.yaml
Labels: preview, deployment

#3071 Make keycloak configurable
  deploy.py
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/_keyclaok-url.tpl
  kubernetes/loculus/templates/keycloak-config-map.yaml
  kubernetes/loculus/templates/keycloak-deployment.yaml
  kubernetes/loculus/values.yaml
Labels: preview, deployment

#3126 fix(kubernetes): don't create `external_metadata_updater` user when `disableEnaSubmission`
  kubernetes/loculus/templates/keycloak-config-map.yaml
Labels: deployment, config

#3120 chore(website): Replace ManagedErrorFeedback with react-toastify
  website/src/components/Edit/EditPage.tsx
  website/src/components/ReviewPage/ReviewPage.tsx
  website/src/components/SeqSetCitations/SeqSetForm.tsx
  website/src/components/SeqSetCitations/SeqSetItem.tsx
  website/src/components/SeqSetCitations/SeqSetItemActions.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/components/Submission/RevisionForm.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
  website/src/components/Submission/SubmissionForm.tsx
  website/src/components/common/ManagedErrorFeedback.tsx
Labels: preview

#3128 chore(website): Remove deprecated confirmation dialogs
  website/src/components/DeprecatedConfirmationDialog.tsx
  website/src/components/Edit/EditPage.tsx
Labels: preview, format_me

#3124 feat(ingest, backend): do not approve curated revisions (by users other than insdc_ingest_user), send notification if ingest wants to revise a curated sequence
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SequenceEntriesView.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ApproveProcessedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  ingest/scripts/call_loculus.py
  ingest/scripts/compare_hashes.py
  ingest/tests/test_data_cchf/previous_submissions.json
  kubernetes/loculus/templates/ingest-deployment.yaml
Labels: preview

#3129 feat(website): improve css for markdown pages
  website/src/styles/mdcontainer.scss
Labels: preview

#3141 fix: allow versionComment to be user submitted, emit it correctly
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/loculus-preprocessing-config.yaml
  website/tests/pages/submission/template.spec.ts
Labels: preview

#3138 feat(ci): dump current db schema automatically
  .github/workflows/schema-dump.yml
  backend/docs/db/schema.sql
Labels: update_db_schema
