Repository loculus-project/loculus, pull requests merged in 2024-09, with the labels that each got.

#2667 fix(website): revert hotfix
  website/src/components/SearchPage/DownloadDialog/generateDownloadUrl.ts
Labels: preview

#2657 feat(k8s): allow addition of response header "X-Robots-Tag: noindex, nofollow"
  kubernetes/loculus/templates/ingressroute.yaml
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview, review please

#2685 fix(website): fix resizing issue on DocsMenu
  website/src/components/Navigation/DocsMenu.tsx
Labels: preview, review please

#1914 feat(backend): don't require authentication for /get-released-data
  backend/.gitignore
  backend/README.md
  backend/build.gradle
  backend/gradle.properties
  backend/src/main/kotlin/org/loculus/backend/auth/AuthenticatedUser.kt
  backend/src/main/kotlin/org/loculus/backend/config/SecurityConfig.kt
  backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/RequestAuthorization.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  kubernetes/loculus/silo_import_job.sh
  kubernetes/loculus/templates/_config-processor.tpl
  kubernetes/loculus/templates/keycloak-config-map.yaml
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_e2e_and_dev.yaml
Labels: preview, format_me

#2709 deps(backend): bump gradle to 8.8 from 8.5
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.properties
Labels: preview

#2707 fix(deployment): Only try to include SILO-specific config in the LAPIS/SILO configmap if it is actually defined
  kubernetes/loculus/templates/_siloDatabaseConfig.tpl
Labels: preview, review please

#2712 docs: Remove date from "my first loculus" tutorial
  docs/src/content/docs/for-administrators/my-first-loculus.md
Labels: preview

#2716 feat(e2e): Add tests that data submitted as restricted stays restricted state
  website/README.md
  website/src/components/ReviewPage/ReviewPage.tsx
  website/tests/pages/review/index.spec.ts
  website/tests/pages/submission/index.spec.ts
  website/tests/util/backendCalls.ts
  website/tests/util/prepareDataToBe.ts
Labels: preview

#2723 Add load example data to no-aligned-organism
  website/src/components/Submission/DataUploadForm.tsx
Labels: preview, format_me

#2725 feat(website): resize images to max-size used in website
  website/public/images/organisms/cchf.jpg
  website/public/images/organisms/cchf_small.jpg
  website/public/images/organisms/ebolasudan.jpg
  website/public/images/organisms/ebolasudan_small.jpg
  website/public/images/organisms/ebolazaire.jpg
  website/public/images/organisms/ebolazaire_small.jpg
  website/public/images/organisms/wnv.jpg
  website/public/images/organisms/wnv_small.jpg
  website/scripts/process_images.sh
Labels: preview

#2728 Remove '-' from list of allowed symbols in unaligned sequences.
  backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequenceEntryValidator.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
  preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py
Labels: preview

#2680 fix(prepro): Label a sequence with error if not all input segments align
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
Labels: preview

#2764 Table update tracker anya
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UpdateTrackerTable.kt
  backend/src/main/resources/db/migration/V1.2__add_table_update_tracker.sql
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  kubernetes/loculus/silo_import_job.sh
  kubernetes/loculus/silo_import_wrapper.sh
Labels: preview

#2777 Add_count_in_header_test
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
  kubernetes/loculus/values.yaml
Labels: preview

#2772 Add latitude and longitude to default metadata values.
  kubernetes/loculus/values.yaml
Labels: preview, review please

#2773 fix(backend, silo-preprocessing): add new header x-total-records to get-released-data to enable streaming result verification
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  kubernetes/loculus/silo_import_job.sh
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
Labels: preview

#2802 feat(deployment): Allow detailed customizable resources
  kubernetes/loculus/templates/_resources.tpl
  kubernetes/loculus/templates/docs-preview.yaml
  kubernetes/loculus/templates/ena-submission-deployment.yaml
  kubernetes/loculus/templates/ingest-deployment.yaml
  kubernetes/loculus/templates/keycloak-deployment.yaml
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
  kubernetes/loculus/templates/loculus-website.yaml
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_e2e_and_dev.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#2808 feat(ci): Make deploy script cleaner: use temp file, add logs
  deploy.py
Labels: preview

#2814 feat(website): Only count latest versions for stats on main page
  website/src/components/IndexPage/getOrganismStatistics.ts
Labels: preview, format_me

#2731 feat: use etags for caching to avoid backend/db load when idle
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UpdateTrackerTable.kt
  backend/src/main/resources/db/migration/V1.2__add_table_update_tracker.sql
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  kubernetes/loculus/silo_import_job.sh
  kubernetes/loculus/silo_import_wrapper.sh
Labels: preview, format_me

#2829 feat(ingest): Update datasets package in ingest
  ingest/environment.yml
Labels: preview, review please

#2813 Add countries in NIH list which are missing from ENA list
  kubernetes/loculus/values.yaml
Labels: preview

#2417 feat(ena-submission): Upload ena submission results to Loculus
  .github/workflows/e2e-k3d.yml
  .github/workflows/ena-submission-tests.yaml
  backend/README.md
  backend/src/main/resources/db/migration/V1.3__update_view.sql
  ena-submission/Dockerfile
  ena-submission/ENA_submission.md
  ena-submission/README.md
  ena-submission/Snakefile
  ena-submission/config/config.yaml
  ena-submission/config/defaults.yaml
  ena-submission/environment.yml
  ena-submission/flyway/sql/V1.1__add_center_name.sql
  ena-submission/scripts/call_loculus.py
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/create_sample.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/ena_types.py
  ena-submission/scripts/get_ena_submission_list.py
  ena-submission/scripts/notifications.py
  ena-submission/scripts/submission_db_helper.py
  ena-submission/scripts/test_ena_submission.py
  ena-submission/scripts/trigger_submission_to_ena.py
  ena-submission/scripts/upload_external_metadata_to_loculus.py
  ena-submission/test/approved_ena_submission_list_test.json
  ena-submission/test/test_project_response.xml
  ena-submission/test/test_sample_request.xml
  ena-submission/test/test_sample_response.xml
  ena-submission/test/text_project_request.xml
  kubernetes/loculus/templates/ena-submission-deployment.yaml
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview, insdc

#2833 fix: don't ingest region as geoLocAdmin2 (it's continent)
  kubernetes/loculus/values.yaml
Labels: preview

#2653 [don't merge without prior discussion] fix: don't sort author lists, except for segment grouping purposes
  ingest/scripts/call_loculus.py
  ingest/scripts/group_segments.py
  ingest/scripts/prepare_metadata.py
Labels: bug, preview, ingest, high_priority

#2844 feat(ingest): Raise ingest error if we ever have multiple loculus accession for one insdc accession in loculus
  ingest/scripts/call_loculus.py
Labels: preview

#2852 test(backend): test `/get-original-metadata` locked during new submissions
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt
Labels: preview

#2851 feat(website): One tab for all protein sequences
  website/src/components/SequenceDetailsPage/SequenceContainer.spec.tsx
  website/src/components/SequenceDetailsPage/SequenceViewer.tsx
  website/src/components/SequenceDetailsPage/SequencesContainer.tsx
  website/tests/pages/sequences/accession.spec.ts
  website/tests/pages/sequences/sequences.page.ts
Labels: preview

#2857 feat(ingest/backend): add and use 'x-total-record' header for /get-original-metadata endpoint
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt
  ingest/scripts/call_loculus.py
Labels: preview

#2860 Move argoCD sync options to the right place in ingest, and add reloader
  kubernetes/loculus/templates/ingest-deployment.yaml
Labels: preview

#2859 feat(deployment): ingest version checking
  kubernetes/loculus/templates/ingest-config.yaml
  kubernetes/loculus/templates/ingest-deployment.yaml
Labels: preview

#2862 fix(deployment): suspend loculus-revoke-and-regroup-cronjob
  kubernetes/loculus/templates/ingest-deployment.yaml
Labels: preview

#2863 Remove reloader from CronJob
  kubernetes/loculus/templates/ingest-deployment.yaml
Labels: preview

#2861 No actual change
  README.md
Labels: preview

#2768 feat(backend,prepro): use etag to reduce database load
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ExtractUnprocessedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  kubernetes/loculus/silo_import_job.sh
  preprocessing/dummy/main.py
  preprocessing/nextclade/environment.yml
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
  preprocessing/nextclade/src/loculus_preprocessing/datatypes.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
Labels: preview

#2845 Add INSDC accession to results of ena submission and upload to backend.
  ena-submission/README.md
  ena-submission/Snakefile
  ena-submission/config/defaults.yaml
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/create_sample.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/upload_external_metadata_to_loculus.py
Labels: preview

#2874 Update ena-submission config
  .github/workflows/ena-submission-image.yaml
  .github/workflows/update-argocd-metadata.yml
  deploy.py
  ena-submission/Snakefile
  ena-submission/config/defaults.yaml
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/ena-submission-config.yaml
  kubernetes/loculus/values.yaml
Labels: preview

#2875 Reduce ena submission induced db load
  ena-submission/Snakefile
  ena-submission/config/defaults.yaml
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/create_sample.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/submission_db_helper.py
  ena-submission/scripts/test_ena_submission.py
  ena-submission/scripts/trigger_submission_to_ena.py
  ena-submission/scripts/upload_external_metadata_to_loculus.py
Labels: preview

#2877 fix(ingest): Update metadata hash calculation, do not include empty fields in hash
  ingest/README.md
  ingest/scripts/group_segments.py
  ingest/scripts/prepare_metadata.py
Labels: preview

#2890 fix(ena-submission): Use db url instead of host for connections, do not hardcode db name
  .github/workflows/build-arm-images.yaml
  ena-submission/README.md
  ena-submission/config/config.yaml
  ena-submission/flyway/conf/flyway.conf
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/create_sample.py
  ena-submission/scripts/get_ena_submission_list.py
  ena-submission/scripts/submission_db_helper.py
  ena-submission/scripts/trigger_submission_to_ena.py
  ena-submission/scripts/upload_external_metadata_to_loculus.py
  kubernetes/loculus/templates/ena-submission-deployment.yaml
Labels: preview

#2887 fix(prepro): Add execption handling to identity and call_function
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
Labels: preview

#2899 fix(website): Change submitting group ID displayName
  kubernetes/loculus/templates/_common-metadata.tpl
Labels: preview

#2896 fix(ena-submission): Parse get analysis process response better for single segment case, return partial results and submit projects with holdUntilDate
  ena-submission/scripts/create_assembly.py
  ena-submission/scripts/create_project.py
  ena-submission/scripts/create_sample.py
  ena-submission/scripts/ena_submission_helper.py
  ena-submission/scripts/ena_types.py
  ena-submission/scripts/test_ena_submission.py
  ena-submission/test/get_ena_analysis_process_response.json
Labels: preview

#2848 Get list of accessions to not ingest from ena-submission schema.
  ena-submission/config/config.yaml
  ingest/README.md
  ingest/Snakefile
  ingest/config/defaults.yaml
  ingest/environment.yml
  ingest/scripts/filter_out_depositions.py
  ingest/scripts/get_loculus_depositions.py
  ingest/tests/config_cchf/config.yaml
  ingest/tests/test_data_cchf/biosample_accessions_to_exclude.tsv
  ingest/tests/test_data_cchf/insdc_accessions_to_exclude.tsv
  ingest/tests/test_data_cchf/metadata_post_extract.tsv
  ingest/tests/test_ingest.py
  kubernetes/loculus/templates/ingest-config.yaml
  kubernetes/loculus/templates/ingest-deployment.yaml
Labels: preview

#2903 Move version comment to common metadata
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/keycloak-config-map.yaml
  kubernetes/loculus/values.yaml
Labels: preview

#2797 feat(website): Add custom gitHub url setting
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/components/Navigation/Navigation.astro
  website/src/components/Navigation/SandwichMenu.tsx
  website/src/layouts/BaseLayout.astro
  website/src/types/config.ts
Labels: preview, format_me
