Repository loculus-project/loculus, pull requests merged in 2024-11, with the labels that each got.

#3147 feat(docs): Add an image-border
  website/README.md
  website/src/styles/mdcontainer.scss
Labels: format_me

#3149 doc: add comment to country list in values.yaml
  kubernetes/loculus/values.yaml
Labels: review please

#3157 docs: sequence submission and submission approval
  docs/src/content/docs/for-users/approve-submissions.md
  docs/src/content/docs/for-users/create-manage-groups.md
  docs/src/content/docs/for-users/submit-sequences.md
Labels: preview

#3159 fix(confg): remove Plausible from default additionalHeadHTML
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#3163 feat!(website): add redirects to docs and add search sequences docs
  docs/astro.config.mjs
  docs/src/content/docs/for-users/search-sequences.md
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/searchFormHelpDocsUrl.ts
  website/src/pages/api-documentation/authenticationApiDocsUrl.ts
  website/src/pages/api-documentation/index.astro
  website/src/pages/docs/how-to/search-sequences-website.mdx
Labels: preview

#3165 feat(website): remove empty Governance and Status pages
  website/src/pages/-testpage/index.mdx
  website/src/pages/status/index.astro
  website/src/routes/bottomNavigationItems.ts
  website/src/routes/routes.ts
  website/tests/pages/navigation.spec.ts
Labels: preview

#3166 feat!(website): change link to the data upload docs
  website/src/components/Submission/DataUploadForm.tsx
  website/src/components/Submission/dataUploadDocsUrl.ts
Labels: preview

#3062 feat(website): redesign organism card
  website/public/images/organisms/cchf_small.jpg
  website/public/images/organisms/ebolasudan_small.jpg
  website/public/images/organisms/ebolazaire_small.jpg
  website/public/images/organisms/wnv_small.jpg
  website/scripts/process_images.sh
  website/src/components/IndexPage/OrganismCard.astro
Labels: preview

#3178 docs: Fixes to my-first-loculus.md
  docs/src/content/docs/for-administrators/my-first-loculus.md
Labels: preview

#3183 feat(ena-submission, ingest): Submit more geolocation information, filter out all versions of an ENA accession
  ena-submission/config/defaults.yaml
  ena-submission/src/ena_deposition/create_assembly.py
  ena-submission/src/ena_deposition/create_sample.py
  ena-submission/test/approved_ena_submission_list_test.json
  ena-submission/test/test_sample_request.xml
  ingest/scripts/filter_out_depositions.py
  ingest/tests/test_data_cchf/ncbi_dataset.zip
Labels: preview

#3075 feat(ci, ingest, prepro): Allow custom nextclade datasets
  ingest/Snakefile
  kubernetes/loculus/templates/ingest-config.yaml
  kubernetes/loculus/templates/loculus-preprocessing-config.yaml
  kubernetes/loculus/values.yaml
  preprocessing/nextclade/README.md
  preprocessing/nextclade/src/loculus_preprocessing/config.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
Labels: needs-ppx-values-pr

#3206 fix: use github pages to host sequences not raw.githubusercontent to avoid 403 errors/rate limits
  kubernetes/loculus/values.yaml
Labels: review please

#3125 feat: support filtering for warnings only on the review page
  backend/docs/db/schema.sql
  backend/docs/plantuml/sequenceInitialSubmission.puml
  backend/docs/plantuml/sequenceInitialSubmission.svg
  backend/docs/plantuml/sequenceRevocation.puml
  backend/docs/plantuml/sequenceRevocation.svg
  backend/docs/plantuml/statusChange.puml
  backend/docs/plantuml/statusChange.svg
  backend/docs/runtime_view.md
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/AccessionPreconditionValidator.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SequenceEntriesView.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/resources/db/migration/V1.5__update_sequence_entries_view_status_field.sql
  backend/src/test/kotlin/org/loculus/backend/controller/TestHelpers.kt
  backend/src/test/kotlin/org/loculus/backend/controller/debug/DeleteAllSequenceDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ApproveProcessedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/DeleteSequencesEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetDataToEditEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetSequencesEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ReviseEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/RevokeEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionJourneyTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEditedSequenceEntryVersionEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
  docs/src/content/docs/for-users/approve-submissions.md
  website/src/components/ConfirmationDialog.tsx
  website/src/components/ReviewPage/ReviewCard.tsx
  website/src/components/ReviewPage/ReviewPage.spec.tsx
  website/src/components/ReviewPage/ReviewPage.tsx
  website/src/components/Submission/SubmissionGroupSelector.tsx
  website/src/hooks/useSubmissionOperations.ts
  website/src/services/backendApi.ts
  website/src/types/backend.ts
  website/tailwind.config.cjs
  website/tests/pages/review/review.page.ts
  website/tsconfig.json
  website/vitest.setup.ts
Labels: preview, update_db_schema

#3216 feat(website): make welcome message configurable
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/components/IndexPage/WelcomeMessage.astro
  website/src/pages/index.astro
  website/src/types/config.ts
Labels: preview

#3212 feat!: allow disabling of seqsets [CFG]
  .idea/runConfigurations/BackendApplicationKt.run.xml
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SeqSetCitationsController.kt
  backend/src/test/kotlin/org/loculus/backend/controller/seqsetcitations/SeqSetEndpointsDisabledTest.kt
  backend/src/test/resources/application.properties
  backend/start_dev.sh
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/values.yaml
  website/src/components/Navigation/Navigation.astro
  website/src/components/Navigation/SandwichMenu.tsx
  website/src/config.ts
  website/src/pages/seqsets/[seqSetId].[version].astro
  website/src/pages/seqsets/index.astro
  website/src/routes/navigationItems.ts
  website/src/types/config.ts
Labels: preview

#3028 feat!: Add substring search support for more fields
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/_siloDatabaseConfig.tpl
  kubernetes/loculus/values.yaml
  website/src/types/config.ts
  website/src/utils/search.ts
Labels: preview

#3207 feat: use 'display name' for the metadata labels on the reviewp.
  website/src/components/ReviewPage/ReviewCard.tsx
  website/src/components/ReviewPage/ReviewPage.spec.tsx
  website/src/components/ReviewPage/ReviewPage.tsx
  website/src/config.ts
  website/src/pages/[organism]/submission/[groupId]/review.astro
Labels: preview

#3227 fix(backend): fix the inability to access revision form due to checking status
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetDataToEditEndpointTest.kt
Labels: preview

#3233 perf(backend): remove null values before storing processed data in database
  backend/src/main/kotlin/org/loculus/backend/service/submission/CompressionService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/MetadataSchemaEnforcementService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  kubernetes/loculus/templates/loculus-database-standin.yaml
Labels: preview, format_me

#3234 chore(backend): fix flaky test that made wrong assumptions about order being guaranteed
  backend/src/test/kotlin/org/loculus/backend/controller/submission/DeleteSequencesEndpointTest.kt
Labels: backend, review please, tests

#3223 make it possible to disable the submit workflow on the website
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/config.ts
  website/src/middleware.ts
  website/src/middleware/submissionPagesDisablingMiddleware.ts
  website/src/pages/organism-selector/[redirectTo].astro
  website/src/routes/navigationItems.ts
  website/src/types/config.ts
Labels: preview

#3255 feat(config): allow dev standin dbs to be semi-persistent through values.yaml
  kubernetes/loculus/templates/keycloak-database-standin.yaml
  kubernetes/loculus/templates/loculus-database-standin.yaml
  kubernetes/loculus/values.yaml
Labels: preview, config

#3247 chore(backend): fix some more racy backend tests by not asserting on exact order
  backend/src/test/kotlin/org/loculus/backend/controller/TestHelpers.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ApproveProcessedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/DeleteSequencesEndpointTest.kt
Labels: backend, review please

#3246 fix(backend): Fix submitter of revoked sequences to be the revoker
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/TestHelpers.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/RevokeEndpointTest.kt
Labels: preview

#3232 feat(backend): Don't store null fields of processed data for perf, emit exactly current schema in get-released-data - imputing with null
  backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedDataPostprocessor.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedMetadataPostprocessor.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitExternalMetadataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/CompressionServiceTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/ProcessedMetadataPostprocessorTest.kt
  backend/src/test/resources/backend_config.json
Labels: preview, format_me

#3276 docs: add Plausible analytics
  docs/astro.config.mjs
Labels: preview

#3259 fix(backend): add foreign key to delete preprocessed data
  backend/docs/db/schema.sql
  backend/src/main/resources/db/migration/V1.6__add_sequence_entries_preprocessed_data_foreign_key.sql
  backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
  backend/src/test/kotlin/org/loculus/backend/controller/debug/DeleteAllSequenceDataEndpointTest.kt
Labels: preview, update_db_schema

#3309 docs: add tutorial for setup with k3d and nginx
  docs/astro.config.mjs
  docs/src/content/docs/for-administrators/setup-with-k3d-and-nginx.mdx
Labels: preview
