Repository loculus-project/loculus, pull requests merged in 2025-03, with the labels that each got.

#3783 fix(docs): improve helm template values docs
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/values.schema.json
Labels: preview

#3799 fix(website): fasta was incorrectly generated with empty segments
  website/src/components/Edit/InputForm.spec.tsx
  website/src/components/Edit/InputForm.tsx
Labels: preview

#3796 fix(deployment): Helm Schema - Add `additionalProperties: false` where it was missing
  kubernetes/loculus/values.schema.json
Labels: deployment

#3777 feat(website): active filter view above Search UI table
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
  website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/fields/MutationField.tsx
  website/src/components/common/ActiveFilters.spec.tsx
  website/src/components/common/ActiveFilters.tsx
  website/src/utils/mutation.spec.ts
  website/src/utils/mutation.ts
  website/src/utils/search.ts
Labels: preview

#3803 feat(config): correct yaml syntax for prepro
  kubernetes/loculus/values.yaml
Labels: preview

#3776 chore!: move preview/ppx specific Helm Chart settings out of the default values
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#3817 fix(website): Fix the format of the reference dialog
  website/src/components/SequenceDetailsPage/ReferenceSequenceLinkButton.tsx
Labels: website, preview

#3834 feat(deployment): set LAPIS max 75% of container memory
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
Labels: preview, preview-ppx

#3839 fix(deployment): change lapis livenessProbe to readinessProbe and use a liveness probe based on health endpoint
  kubernetes/loculus/templates/lapis-deployment.yaml
Labels: preview

#3838 chore: increase number of SILO workers
  kubernetes/loculus/templates/silo-deployment.yaml
Labels: preview

#3812 feat(website): Replace textbox for sequences in edit form with file upload
  integration-tests/tests/pages/singlesubmission.page.ts
  integration-tests/tests/specs/features/submission-flow.spec.ts
  website/src/components/Edit/EditPage.spec.tsx
  website/src/components/Edit/EditPage.tsx
  website/src/components/Edit/InputForm.tsx
  website/src/components/Submission/FileUpload/FileUploadComponent.tsx
  website/src/components/Submission/FileUpload/SequenceEntryUploadComponent.tsx
  website/src/components/Submission/FileUpload/fileProcessing.spec.ts
  website/src/components/Submission/FileUpload/fileProcessing.ts
  website/src/components/Submission/FormOrUploadWrapper.spec.tsx
  website/src/components/Submission/FormOrUploadWrapper.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
Labels: preview

#3841 chore(deployment): increase SILO API max queued
  kubernetes/loculus/templates/silo-deployment.yaml
Labels: preview

#3837 fix(website): Make warning banners show on modal sequence details
  website/src/components/SearchPage/SeqPreviewModal.tsx
  website/src/components/SequenceDetailsPage/SequencesBanner.astro
  website/src/components/SequenceDetailsPage/SequencesBanner.tsx
  website/src/components/SequenceDetailsPage/getTableData.ts
  website/src/pages/seq/[accessionVersion]/index.astro
  website/src/types/lapis.ts
Labels: preview

#3847 fix(kubernetes): make the "empty lineage definition file" valid YAML
  kubernetes/loculus/silo_import_job.sh
Labels: preview

#3813 feat(website): Improve sequence details dropdown a little
  website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.spec.tsx
  website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.tsx
  website/tests/pages/sequences/sequences.page.ts
Labels: preview, format_me

#3846 feat(website): add sequence button to review cards
  .github/workflows/integration-tests.yml
  integration-tests/tests/pages/review.page.ts
  integration-tests/tests/pages/singlesubmission.page.ts
  integration-tests/tests/specs/features/sequence-view.spec.ts
  integration-tests/tests/specs/features/submission-flow.spec.ts
  website/src/components/Edit/EditPage.spec.tsx
  website/src/components/Edit/EditPage.tsx
  website/src/components/ReviewPage/ReviewCard.tsx
  website/src/components/ReviewPage/SequencesDialog.tsx
  website/src/components/common/FixedLengthTextViewer.tsx
Labels: preview

#3762 feat(website): store previewed sequence ID in URL
  integration-tests/tests/pages/search.page.ts
  integration-tests/tests/specs/features/sequence-preview-url.spec.ts
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/SeqPreviewModal.tsx
  website/src/components/SearchPage/Table.tsx
  website/src/hooks/useUrlParamState.ts
Labels: preview

#3867 fix(website): Render timestamp as YYYY-MM-DD instead of UNIX timestamp
  website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
  website/src/components/SearchPage/fields/DateField.spec.tsx
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/common/ActiveFilters.spec.tsx
Labels: discussion, preview

#3869 Revert "chore(deps-dev): bump daisyui from 4.12.23 to 5.0.6 in /website"
  website/package-lock.json
  website/package.json
Labels: preview

#3761 feat!(website): allow selecting fields to download in metadata and default to a shorter selection
  integration-tests/tests/fixtures/sequence.fixture.ts
  integration-tests/tests/pages/review.page.ts
  integration-tests/tests/pages/search.page.ts
  integration-tests/tests/specs/features/download.spec.ts
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/DownloadDialog/DownloadButton.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.spec.ts
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
  website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorButton.tsx
  website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.spec.tsx
  website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.tsx
  website/src/components/SearchPage/SearchFullUI.spec.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/types/config.ts
Labels: preview, format_me

#3871 feat(website): Visualize that a file upload component has data in it already if empty
  integration-tests/playwright.config.ts
  integration-tests/tests/fixtures/group.fixture.ts
  integration-tests/tests/fixtures/sequence.fixture.ts
  integration-tests/tests/pages/review.page.ts
  integration-tests/tests/pages/search.page.ts
  integration-tests/tests/readonly.setup.ts
  integration-tests/tests/specs/features/download.spec.ts
  integration-tests/tests/specs/features/revise-sequence.spec.ts
  integration-tests/tests/specs/features/search.spec.ts
  integration-tests/tests/specs/features/sequence-preview-url.spec.ts
  integration-tests/tests/specs/features/sequence-view.spec.ts
  integration-tests/tests/specs/features/submission-flow.spec.ts
  website/src/components/Edit/EditPage.spec.tsx
  website/src/components/Edit/EditPage.tsx
  website/src/components/Edit/SequencesForm.spec.tsx
  website/src/components/Edit/SequencesForm.tsx
  website/src/components/Submission/FileUpload/FileUploadComponent.spec.tsx
  website/src/components/Submission/FileUpload/FileUploadComponent.tsx
  website/src/components/Submission/FileUpload/fileProcessing.ts
  website/src/pages/[organism]/submission/edit/[accession]/[version].astro
Labels: website, preview

#3811 feat(website): better lineage search
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.spec.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.tsx
  website/src/components/SearchPage/fields/AutoCompleteOptions.ts
  website/src/components/SearchPage/fields/LineageField.spec.tsx
  website/src/components/SearchPage/fields/LineageField.tsx
  website/src/services/lapisApi.ts
  website/src/types/lapis.ts
Labels: website, preview

#3883 refactor(SearchFullUI): Introduce `FilterSchema` class and consolidate scattered functionality in it
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.spec.ts
  website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
  website/src/components/SearchPage/SearchForm.spec.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/fields/AutoCompleteOptions.ts
  website/src/components/SearchPage/fields/LineageField.tsx
  website/src/components/common/ActiveFilters.spec.tsx
  website/src/config.ts
  website/src/pages/[organism]/search/index.astro
  website/src/pages/[organism]/submission/[groupId]/released.astro
  website/src/pages/[organism]/submission/[groupId]/revise.astro
  website/src/pages/[organism]/submission/[groupId]/submit.astro
  website/src/pages/[organism]/submission/edit/[accession]/[version].astro
  website/src/pages/seq/[accessionVersion]/index.astro
  website/src/utils/search.ts
  website/src/utils/serversideSearch.ts
Labels: preview

#3892 fix: Edit form does not incorrectly drop sequence data anymore.
  website/src/components/Edit/SequencesForm.spec.tsx
  website/src/components/Edit/SequencesForm.tsx
  website/src/components/Submission/FileUpload/fileProcessing.ts
Labels: preview

#3895 fix(website): fix handling of certain edgecases for the active filter display
  .github/workflows/integration-tests.yml
  integration-tests/tests/pages/search.page.ts
  integration-tests/tests/specs/features/search/active-filters.spec.ts
  integration-tests/tests/specs/features/search/download.spec.ts
  integration-tests/tests/specs/features/search/override-hidden-fields.ts
  integration-tests/tests/specs/features/search/search.spec.ts
  website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/fields/DateField.spec.tsx
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/SearchPage/fields/DateRangeField.spec.tsx
  website/src/components/SearchPage/fields/DateRangeField.tsx
  website/src/components/SearchPage/fields/NormalTextField.tsx
  website/src/components/common/ActiveFilters.spec.tsx
  website/src/components/common/ActiveFilters.tsx
Labels: preview

#3902 feat!(deployment): Standardize image config in Helm Chart
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/lapis-deployment.yaml
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/templates/loculus-website.yaml
  kubernetes/loculus/templates/silo-deployment.yaml
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
Labels: preview

#3912 feat(backend): add Files table
  backend/docs/db/schema.sql
  backend/src/main/kotlin/org/loculus/backend/service/files/FilesTable.kt
  backend/src/main/resources/db/migration/V1.11__file_sharing.sql
Labels: update_db_schema
