Repository loculus-project/loculus, pull requests merged in 2025-07, with the labels that each got.

#4540 fix(website): remove lineage aliases from drop down
  website/src/components/SearchPage/fields/AutoCompleteOptions.ts
  website/src/components/SearchPage/fields/LineageField.spec.tsx
Labels: preview

#4571 chore(deposition): add pip install -e . to docs, add type packages to env
  ena-submission/README.md
  ena-submission/environment.yml
Labels: review please

#4576 enable searching for genotype on multi-pathogen pages
  ingest/scripts/prepare_metadata.py
  kubernetes/loculus/values.yaml
Labels: preview

#4583 multipath: match dash too in linkouts
  website/src/utils/templateProcessor.ts
Labels: preview

#4619 chore(deployment): Remove "dummy organism without consensus sequences" from `defaultOrganism`
  kubernetes/loculus/values.yaml
Labels: preview

#4622 feat(k8s): allow disabling organism by setting "enabled: false"
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/_enabledOrganisms.tpl
  kubernetes/loculus/templates/_urls.tpl
  kubernetes/loculus/templates/ingest-config.yaml
  kubernetes/loculus/templates/ingest-deployment.yaml
  kubernetes/loculus/templates/lapis-deployment.yaml
  kubernetes/loculus/templates/lapis-ingress.yaml
  kubernetes/loculus/templates/lapis-service.yaml
  kubernetes/loculus/templates/lapis-silo-database-config.yaml
  kubernetes/loculus/templates/loculus-preprocessing-config.yaml
  kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
  kubernetes/loculus/templates/silo-deployment.yaml
  kubernetes/loculus/templates/silo-service.yaml
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
Labels: preview

#4617 fix(backend): document files api correctly using openapi annotations
  backend/src/main/kotlin/org/loculus/backend/controller/FilesController.kt
Labels: preview

#4614 feat(prepro): use submittedAt date as upperBound in parse_date_into_range instead of processing time
  preprocessing/nextclade/environment.yml
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
  preprocessing/nextclade/src/loculus_preprocessing/datatypes.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/tests/factory_methods.py
  preprocessing/nextclade/tests/test_processing_functions.py
Labels: preview

#4644 [cli-branch] feat(website): add loculus info endpoint
  website/src/pages/loculus-info/index.ts
Labels: preview, codex

#4650 fix(deposition): make submission list upload to Slack work again
  ena-submission/src/ena_deposition/notifications.py
Labels: preview

#4700 docs: Move glossary to 'Reference' section
  architecture_docs/12_glossary.md
  docs/astro.config.mjs
  docs/src/content/docs/for-administrators/build-new-preprocessing-pipeline.md
  docs/src/content/docs/for-administrators/configuring-extra-files.md
  docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
  docs/src/content/docs/for-administrators/pipeline-concept.md
  docs/src/content/docs/for-administrators/schema-designs.md
  docs/src/content/docs/for-users/authenticate-via-api.md
  docs/src/content/docs/for-users/create-manage-groups.md
  docs/src/content/docs/for-users/edit-account.md
  docs/src/content/docs/for-users/revise-sequences.md
  docs/src/content/docs/introduction/system-overview.md
  docs/src/content/docs/reference/glossary.md
Labels: preview

#4719 feat(deposition): Upload external metadata as soon as available, not just when complete
  ena-submission/scripts/test_ena_submission_integration.py
  ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
Labels: preview

#4646 feat(cli): Command-line interface for Loculus
  .github/workflows/cli-tests.yml
  .github/workflows/integration-tests.yml
  cli/.python-version
  cli/README.md
  cli/pyproject.toml
  cli/src/loculus_cli/__init__.py
  cli/src/loculus_cli/__main__.py
  cli/src/loculus_cli/api/__init__.py
  cli/src/loculus_cli/api/backend.py
  cli/src/loculus_cli/api/lapis.py
  cli/src/loculus_cli/api/models.py
  cli/src/loculus_cli/auth/__init__.py
  cli/src/loculus_cli/auth/client.py
  cli/src/loculus_cli/cli.py
  cli/src/loculus_cli/commands/__init__.py
  cli/src/loculus_cli/commands/auth.py
  cli/src/loculus_cli/commands/config.py
  cli/src/loculus_cli/commands/get.py
  cli/src/loculus_cli/commands/group.py
  cli/src/loculus_cli/commands/instance.py
  cli/src/loculus_cli/commands/organism.py
  cli/src/loculus_cli/commands/release.py
  cli/src/loculus_cli/commands/schema.py
  cli/src/loculus_cli/commands/status.py
  cli/src/loculus_cli/commands/submit.py
  cli/src/loculus_cli/config.py
  cli/src/loculus_cli/instance_info.py
  cli/src/loculus_cli/types.py
  cli/src/loculus_cli/utils/__init__.py
  cli/src/loculus_cli/utils/console.py
  cli/src/loculus_cli/utils/guards.py
  cli/src/loculus_cli/utils/metadata_filter.py
  cli/src/loculus_cli/utils/review_utils.py
  cli/uv.lock
  integration-tests/README.md
  integration-tests/playwright.config.ts
  integration-tests/tests/fixtures/cli.fixture.ts
  integration-tests/tests/fixtures/group.fixture.ts
  integration-tests/tests/pages/CliPage.ts
  integration-tests/tests/pages/group.page.ts
  integration-tests/tests/readonly.setup.ts
  integration-tests/tests/specs/cli/auth.spec.ts
  integration-tests/tests/specs/cli/end-to-end-flow.spec.ts
  integration-tests/tests/specs/cli/get.spec.ts
  integration-tests/tests/specs/cli/release.spec.ts
  integration-tests/tests/specs/cli/status.spec.ts
  integration-tests/tests/specs/cli/submit.spec.ts
  website/src/pages/loculus-info/index.ts
Labels: preview

#4692 feat!(kubernetes): [CFG] add support for multiple reference genomes
  backend/src/main/kotlin/org/loculus/backend/config/Config.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/CompressionService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProvider.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequenceEntryValidator.kt
  backend/src/main/kotlin/org/loculus/backend/utils/ParseFastaHeader.kt
  backend/src/test/kotlin/org/loculus/backend/config/BackendSpringConfigTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt
  backend/src/test/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProviderTest.kt
  backend/src/test/resources/backend_config.json
  backend/src/test/resources/backend_config_data_use_terms_disabled.json
  backend/src/test/resources/backend_config_s3.json
  backend/src/test/resources/backend_config_single_segment.json
  docs/src/content/docs/for-administrators/my-first-loculus.md
  docs/src/content/docs/for-administrators/setup-with-k3d-and-nginx.mdx
  docs/src/content/docs/for-administrators/setup-with-kubernetes.md
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/lapis-silo-database-config.yaml
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  website/src/config.ts
  website/src/pages/[organism]/api/_sequences.spec.ts
  website/src/pages/[organism]/api/sequences.ts
  website/src/pages/seq/[accessionVersion].fa/index.ts
  website/src/types/referencesGenomes.ts
Labels: preview

#4748 refactor!(website): enable extra sequence-related nav items in Pathoplexus
  website/src/routes/extraTopNavigationItems.ts
  website/src/routes/navigationItems.ts
Labels: preview

#4766 chore: disable enteroviruses on main (not working), minify image, simplify config
  kubernetes/loculus/values.yaml
  website/public/images/organisms/enterovirus.jpg
Labels: preview
