Repository loculus-project/loculus, pull requests merged in 2025-08, with the labels that each got.

#4802 doc(backend): Add description to `/revise`'s fileMapping param
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
Labels: preview

#4767 feat(ingest): never remove segment field from metadata and filter out nextclade sort matches that are not supported
  ingest/scripts/parse_nextclade_sort_output.py
  ingest/scripts/prepare_metadata.py
  kubernetes/loculus/values.yaml
Labels: preview

#4490 feat(preprocessing): Generate annotations file in the nextclade preprocessing pipeline
  docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
  integration-tests/tests/pages/search.page.ts
  integration-tests/tests/specs/features/annotations.dependent.spec.ts
  kubernetes/loculus/templates/loculus-preprocessing-config.yaml
  kubernetes/loculus/values.yaml
  preprocessing/nextclade/README.md
  preprocessing/nextclade/environment.yml
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
  preprocessing/nextclade/src/loculus_preprocessing/config.py
  preprocessing/nextclade/src/loculus_preprocessing/datatypes.py
  preprocessing/nextclade/src/loculus_preprocessing/embl.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/tests/embl_required_metadata.yaml
  preprocessing/nextclade/tests/factory_methods.py
  preprocessing/nextclade/tests/flatfiles/single_segment.embl
  preprocessing/nextclade/tests/single_segment_config.yaml
  preprocessing/nextclade/tests/test_metadata_processing_functions.py
  preprocessing/nextclade/tests/test_nextclade_preprocessing.py
Labels: preview, format_me

#4818 feat(prepro): update embl flat file descriptions
  integration-tests/tests/specs/features/annotations.dependent.spec.ts
  preprocessing/nextclade/src/loculus_preprocessing/embl.py
  preprocessing/nextclade/tests/flatfiles/single_segment.embl
Labels: preview

#4813 fix(backend): handle PostgreSQL parameter limit for large batch submi…
  backend/src/main/kotlin/org/loculus/backend/service/datauseterms/DataUseTermsDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/files/FilesDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UploadDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/utils/DatabaseConstants.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitLargeBatchTest.kt
Labels: preview

#4815 feat(backend): omit nulls in insertions and sequences and do not require prepro to upload null sequences
  backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedDataPostprocessor.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequenceEntryValidator.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/ProcessedSequencesPostprocessor.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/ProcessedSequencesPostprocessorTest.kt
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/tests/factory_methods.py
  preprocessing/nextclade/tests/test_nextclade_preprocessing.py
  preprocessing/specification.md
Labels: preview

#4835 fix(website): align group icon on review page
  website/src/components/Submission/SubmissionGroupSelector.tsx
Labels: codex

#4830 feat!(website): add menu for viewing in different INSDC dbs
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx
  website/src/components/SequenceDetailsPage/LinkWithMenuComponent.tsx
  website/src/types/config.ts
Labels: preview

#4851 Fix dummy-organism `lineage` field not found error
  kubernetes/loculus/values.yaml
Labels: preview

#4855 feat(ingest): raise an error and notify if override groups have multi…
  ingest/scripts/override_group_segments.py
  ingest/scripts/parse_nextclade_sort_output.py
Labels: preview

#4887 feat!(website): use LAPIS endpoint for rich fasta header download
  website/src/components/SearchPage/DownloadDialog/DownloadDataType.ts
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
  website/src/pages/[organism]/api/_sequences.spec.ts
  website/src/pages/[organism]/api/sequences.ts
  website/tests/api/sequences.spec.ts
Labels: preview

#4881 feat(website): use lg breakpoint for nav bar
  website/src/components/Navigation/Navigation.astro
Labels: codex

#4865 feat!(website): add details page ordering
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  website/src/components/SequenceDetailsPage/getDataTableData.spec.ts
  website/src/components/SequenceDetailsPage/getDataTableData.ts
  website/src/components/SequenceDetailsPage/getTableData.ts
  website/src/components/SequenceDetailsPage/types.ts
  website/src/types/config.ts
Labels: preview, codex
