Repository loculus-project/loculus, pull requests merged in 2025-05, with the labels that each got.

#4074 fix(website): Make the sandwich menu display the site name not 'Loculus'
  website/src/components/Navigation/Navigation.astro
  website/src/components/Navigation/SandwichMenu.tsx
Labels: preview, format_me

#4075 feat(ingest): notify on potential suppression
  ingest/scripts/compare_hashes.py
Labels: preview

#4005 feat(preprocessing, integration tests): strip Ns in preprocessing and improve integration tests
  integration-tests/README.md
  integration-tests/playwright.config.ts
  integration-tests/tests/specs/features/search/active-filters.dependent.spec.ts
  integration-tests/tests/specs/features/search/download.dependent.spec.ts
  integration-tests/tests/specs/features/search/search.dependent.spec.ts
  integration-tests/tests/specs/features/sequence-preview-url.dependent.spec.ts
  integration-tests/tests/specs/features/sequence-view.dependent.spec.ts
  integration-tests/tests/specs/features/trim-ns.spec.ts
  integration-tests/tests/specs/group/creategroup.dependent.spec.ts
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
Labels: preview

#4072 feat(website): use consistent and better field selector
  integration-tests/tests/pages/search.page.ts
  integration-tests/tests/specs/features/search/column-visibility.dependent.spec.ts
  integration-tests/tests/specs/features/search/download.dependent.spec.ts
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/CustomizeModal.tsx
  website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.spec.tsx
  website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/SearchFullUI.spec.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/common/FieldSelectorModal.tsx
  website/src/types/config.ts
  website/src/utils/search.ts
  website/tests/pages/search/index.spec.ts
Labels: preview, format_me

#4092 fix(kubernetes): add preprocessing dockerTag to schema
  kubernetes/loculus/values.schema.json
Labels: preview

#4107 chore(ingest): log basic details about NCBI dataset files
  ingest/Snakefile
Labels: preview

#3858 feat(website): Link-out to external tools
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
  website/src/components/SearchPage/DownloadDialog/LinkOutMenu.spec.tsx
  website/src/components/SearchPage/DownloadDialog/LinkOutMenu.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/pages/[organism]/api/sequences.ts
  website/src/pages/[organism]/search/index.astro
  website/src/types/config.ts
  website/src/utils/templateProcessor.spec.ts
  website/src/utils/templateProcessor.ts
Labels: preview

#4117 fix(website): fix select all/none in FieldSelectorModal
  website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.spec.tsx
  website/src/components/SearchPage/DownloadDialog/FieldSelector/FieldSelectorModal.tsx
Labels: preview

#4121 feat(website): make LinkOuts usable without data use terms
  kubernetes/loculus/values.schema.json
  website/src/components/SearchPage/DownloadDialog/LinkOutMenu.spec.tsx
  website/src/components/SearchPage/DownloadDialog/LinkOutMenu.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
Labels: preview

#4148 fix(website): fix website aria violation
  website/src/components/Navigation/SandwichMenu.tsx
  website/src/components/SandwichIcon.tsx
Labels: codex

#4153 fix(website): Fix spacing around version selector
  website/src/components/SequenceDetailsPage/SequenceEntryHistoryMenu.tsx
Labels: preview, codex

#4144 refactor(website): Refactor ErrorBox anchor styling
  website/src/components/common/ErrorBox.tsx
  website/src/styles/base.scss
Labels: codex

#4130 Fix NDJSON comparison in ingest tests
  ingest/tests/expected_output_cchf/metadata_post_prepare.ndjson
  ingest/tests/test_ingest.py
Labels: codex

#4128 fix(website): Fix group edit error message
  website/src/hooks/useGroupOperations.ts
Labels: codex

#4139 feat(website): truncate review cards
  website/src/components/ReviewPage/ReviewCard.tsx
Labels: codex

#4131 fix(ingest): fix `format_authors` return type
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
Labels: codex

#4133 fix(ingest): Fix BatchIterator variable `current_fasta_header`
  ingest/scripts/call_loculus.py
Labels: codex

#4159 fix(deployment): Rename keycloak template file
  kubernetes/loculus/templates/_keycloak-url.tpl
Labels: codex

#4160 chore(website): Use npm ci in website Dockerfile
  website/Dockerfile
Labels: codex

#4094 chore(kubernetes): update LAPIS to 0.4.5 and SILO to 0.6.0
  kubernetes/loculus/values.yaml
Labels: preview

#4162 feat(website): Add warning when last group member leaves
  website/src/components/User/GroupPage.tsx
Labels: preview, codex

#4136 fix(website): Fix Keycloak account URL protocol handling
  website/src/utils/urlForKeycloakAccountPage.spec.ts
  website/src/utils/urlForKeycloakAccountPage.ts
Labels: format_me, codex

#4138 fix(website): Fix processTemplate multiple placeholder replacement
  website/src/utils/templateProcessor.spec.ts
  website/src/utils/templateProcessor.ts
Labels: codex

#4168 fix(website): Fix error message for invalid metadata file extension upload
  website/src/components/Submission/FileUpload/fileProcessing.spec.ts
  website/src/components/Submission/FileUpload/fileProcessing.ts
Labels: preview, codex

#4188 fix(website): fix version selector alignment
  website/src/components/SearchPage/SeqPreviewModal.tsx
Labels: codex

#4163 Reformat prepro
  .github/workflows/preprocessing-tests.yaml
  kubernetes/loculus/values.yaml
  preprocessing/nextclade/.mypy.ini
  preprocessing/nextclade/README.md
  preprocessing/nextclade/src/loculus_preprocessing/backend.py
  preprocessing/nextclade/src/loculus_preprocessing/datatypes.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
  preprocessing/nextclade/src/loculus_preprocessing/sequence_checks.py
  preprocessing/nextclade/tests/factory_methods.py
  preprocessing/nextclade/tests/test_processing_functions.py
Labels: preview

#4190 chore!(deployment): drop relic reduceResourceRequest option
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values_preview_server.yaml
Labels: codex

#4219 feat(website): warn when link out exceeds recommended sequences
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/DownloadDialog/LinkOutMenu.spec.tsx
  website/src/components/SearchPage/DownloadDialog/LinkOutMenu.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/types/config.ts
Labels: codex

#4205 fix(backend): Check that filenames for file sharing are unique
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/AccessionPreconditionValidator.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/FileMappingPreconditionValidator.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ReviseEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEditedSequenceEntryVersionEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointFileSharingTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
  backend/src/test/resources/backend_config_s3.json
Labels: preview

#4224 fix(website): Check for empty LAPIS responses and raise error
  website/src/utils/createDownloadAPIRoute.ts
Labels: preview

#4226 test(integration): add sequence TSV download test
  integration-tests/tests/specs/features/sequence-tsv-download.dependent.spec.ts
Labels: codex

#4222 feat(kubernetes): update LAPIS to 0.5.1 and enable advanced queries
  kubernetes/loculus/templates/_siloDatabaseConfig.tpl
  kubernetes/loculus/values.yaml
Labels: preview

#4154 chore(website): Remove `label` property in website fields
  website/src/components/SearchPage/SearchForm.spec.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/SearchFullUI.spec.tsx
  website/src/components/SearchPage/fields/AccessionField.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.spec.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.tsx
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/SearchPage/fields/DateRangeField.tsx
  website/src/components/SearchPage/fields/LineageField.spec.tsx
  website/src/components/SearchPage/fields/NormalTextField.tsx
  website/src/components/SequenceDetailsPage/getTableData.spec.ts
  website/src/components/common/FieldSelectorModal.tsx
  website/src/types/config.ts
  website/src/utils/search.ts
Labels: preview, codex

#4237 fix(website): reset sequence preview state when switching
  website/src/components/SearchPage/SearchFullUI.tsx
Labels: preview, codex
