Repository loculus-project/loculus, pull requests merged in 2025-04, with the labels that each got.

#3926 chore: remove comments from PR template
  .github/pull_request_template.md
Labels: discussion

#3937 feat(website): Rename restricted to restricted use in terms selector
  website/src/components/DataUseTerms/DataUseTermsSelector.spec.tsx
  website/src/components/DataUseTerms/DataUseTermsSelector.tsx
Labels: preview

#3947 feat(backend): accept files in /submit-processed-data
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/CompressionService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProvider.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/PreparedProcessedData.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/ProcessedMetadataPostprocessorTest.kt
  backend/src/test/kotlin/org/loculus/backend/utils/EarliestReleaseDateFinderTest.kt
  preprocessing/specification.md
Labels: preview

#3964 feat(website): some small improvements to organism card (rev 2)
  website/src/components/IndexPage/OrganismCard.astro
  website/src/pages/index.astro
Labels: preview

#3965 refactor(website): get rid of zodios in the backend client
  website/src/layouts/BaseLayout.astro
  website/src/pages/[organism]/submission/[groupId]/index.astro
  website/src/pages/[organism]/submission/edit/[accession]/[version].astro
  website/src/pages/seq/[accessionVersion]/getSequenceDetailsTableData.ts
  website/src/services/backendApi.ts
  website/src/services/backendClient.ts
  website/src/services/backendClientFactory.ts
  website/tests/e2e.fixture.ts
  website/tests/util/preprocessingPipeline.ts
Labels: website, preview

#3973 fix(website): Make sequences-file check only happen when consensus sequences are enabled
  website/src/components/Submission/FormOrUploadWrapper.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
Labels: website

#3971 feat(preprocessing): support files in dummy pipeline
  kubernetes/loculus/values.yaml
  preprocessing/dummy/main.py
Labels: preview

#3975 Add new S3 credentials for previews
  kubernetes/loculus/values_preview_server.yaml
  website/src/types/config.ts
Labels: preview

#3976 Fix submission issue
  website/src/components/Submission/FileUpload/FolderUploadComponent.tsx
Labels: preview

#3974 Make file links available in SILO
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt
  kubernetes/loculus/templates/_siloDatabaseConfig.tpl
Labels: preview

#3979 display file fields
  kubernetes/loculus/templates/_common-metadata.tpl
Labels: preview

#3982 test(backend): add MinIO testcontainer
  backend/build.gradle
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/config/Config.kt
  backend/src/main/kotlin/org/loculus/backend/config/S3Config.kt
  backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt
  backend/src/main/resources/application.properties
  backend/src/test/kotlin/org/loculus/backend/config/BackendSpringConfigTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
  backend/src/test/kotlin/org/loculus/backend/controller/files/RequestUploadEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointFileSharingTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/GenerateAccessionFromNumberServiceTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProviderTest.kt
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#4001 chore(preprocessing): disable dummy errors for files
  kubernetes/loculus/values.yaml
Labels: preview

#3985 feat(website): Strip `\r` and `\n` on paste into text field
  website/src/components/SearchPage/fields/TextField.spec.tsx
  website/src/components/SearchPage/fields/TextField.tsx
Labels: preview

#4000 render file list with file names and clickable links
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  kubernetes/loculus/templates/_common-metadata.tpl
  website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx
Labels: preview

#4004 feat(website): remove `whitespace-wrap` as undefined in tailwind
  website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx
Labels: preview

#4027 chore(deployment): remove reloader
  deploy.py
  kubernetes/loculus/templates/docs-preview.yaml
  kubernetes/loculus/templates/ena-submission-deployment.yaml
  kubernetes/loculus/templates/ingest-deployment.yaml
  kubernetes/loculus/templates/keycloak-database-standin.yaml
  kubernetes/loculus/templates/keycloak-deployment.yaml
  kubernetes/loculus/templates/lapis-deployment.yaml
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
  kubernetes/loculus/templates/loculus-website.yaml
  kubernetes/loculus/templates/silo-deployment.yaml
Labels: preview

#4028 feat(config): add silo readinessProbe
  kubernetes/loculus/templates/silo-deployment.yaml
Labels: preview

#4034 feat(deployment): timestamp pods on deployment to force restart of all pods on every deployment
  kubernetes/loculus/templates/docs-preview.yaml
  kubernetes/loculus/templates/ena-submission-deployment.yaml
  kubernetes/loculus/templates/ingest-deployment.yaml
  kubernetes/loculus/templates/keycloak-database-standin.yaml
  kubernetes/loculus/templates/keycloak-deployment.yaml
  kubernetes/loculus/templates/lapis-deployment.yaml
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/templates/loculus-preprocessing-deployment.yaml
  kubernetes/loculus/templates/loculus-website.yaml
  kubernetes/loculus/templates/silo-deployment.yaml
Labels: preview

#4042 fix(ingest): handle revocations correctly in call_loculus
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  ingest/scripts/call_loculus.py
  ingest/scripts/compare_hashes.py
Labels: preview

#4040 fix(backend,ingest): handle revoked sequences in /get-original-metadata, they have null metadata
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetOriginalMetadataEndpointTest.kt
  ingest/README.md
  ingest/scripts/call_loculus.py
  ingest/scripts/compare_hashes.py
Labels: preview

#4025 file sharing: Add integration tests
  backend/src/main/kotlin/org/loculus/backend/api/FileTypes.kt
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/config/S3Config.kt
  backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt
  backend/start_dev.sh
  deploy.py
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/tests/fixtures/sequence.fixture.ts
  integration-tests/tests/pages/singlesubmission.page.ts
  integration-tests/tests/pages/submission.page.ts
  integration-tests/tests/readonly.setup.ts
  integration-tests/tests/specs/features/file-sharing.spec.ts
  integration-tests/tests/specs/features/search/override-hidden-fields.ts
  integration-tests/tests/specs/features/sequence-view.spec.ts
  integration-tests/tests/specs/features/single-submit.spec.ts
  integration-tests/tests/specs/features/submission-flow.spec.ts
  kubernetes/loculus/templates/_s3-endpoint.tpl
  kubernetes/loculus/templates/ingressroute.yaml
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/templates/minio-deployment.yaml
  kubernetes/loculus/templates/minio-service.yaml
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#4046 feat(ingest): upload tzst compressed ncbi datasets packages to reduce traffic
  .github/workflows/datasets-mirror.yml
  ingest/.gitignore
  ingest/Snakefile
  ingest/tests/test_data_cchf/ncbi_dataset/data/data_report.jsonl
  ingest/tests/test_ingest.py
Labels: preview

#4008 fix(ingest): ensure when processing alignment that highest scoring al…
  ingest/Snakefile
  ingest/environment.yml
  ingest/scripts/parse_alignment_output.py
  ingest/scripts/parse_nextclade_sort_output.py
  ingest/scripts/prepare_metadata.py
  ingest/tests/expected_output_cchf/revise_metadata.tsv
  ingest/tests/test_data_cchf/sequences.fasta
  ingest/tests/test_ingest.py
Labels: preview
