Repository loculus-project/loculus, pull requests merged in 2025-02, with the labels that each got.

#3601 chore(kubernetes): update to LAPIS 0.3.13, SILO 0.5.2
  kubernetes/loculus/values.yaml
Labels: preview

#3609 feat!(deployment): allow ena submission cronjob resources to be specified in values
  kubernetes/loculus/templates/ena-submission-deployment.yaml
  kubernetes/loculus/values.yaml
Labels: preview

#3608 feat(deposition): stream get-released-data in cronjob to avoid OOM
  ena-submission/scripts/get_ena_submission_list.py
  ena-submission/src/ena_deposition/call_loculus.py
Labels: preview

#3567 fix(website): Don't propagate date parsing errors to concatenated fields
  preprocessing/nextclade/src/loculus_preprocessing/processing_functions.py
Labels: preview

#3617 chore(deposition): Improve deposition logging with ruff suggestions
  ena-submission/src/ena_deposition/__main__.py
  ena-submission/src/ena_deposition/call_loculus.py
  ena-submission/src/ena_deposition/create_assembly.py
  ena-submission/src/ena_deposition/create_project.py
  ena-submission/src/ena_deposition/create_sample.py
  ena-submission/src/ena_deposition/ena_submission_helper.py
  ena-submission/src/ena_deposition/notifications.py
  ena-submission/src/ena_deposition/trigger_submission_to_ena.py
  ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
Labels: preview

#3625 Simplify download URLs generated by Download button (exclude empty fields)
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
Labels: preview

#3628 fix(website): avoid duplicated items in download url and respect choice to include old versions
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
Labels: preview, format_me

#3634 feat!(website): make metadata docs generally available
  website/src/components/MetadataTable.astro
  website/src/components/OrganismMetadataTable/OrganismMetadataTable.tsx
  website/src/components/OrganismMetadataTable/OrganismMetadataTableSelector.tsx
  website/src/components/OrganismMetadataTableSelector.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/components/Submission/metadataFormatDocsUrl.ts
  website/src/pages/[organism]/submission/metadataformat.astro
  website/src/pages/docs/concepts/metadataformat.mdx
Labels: preview

#3635 feat(website): Make all metadata sections in format page expanded by default
  website/src/components/OrganismMetadataTable/OrganismMetadataTable.tsx
Labels: preview, format_me

#3468 feat!: Allow disabling data use terms
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/config/Config.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionControllerDescriptions.kt
  backend/src/main/kotlin/org/loculus/backend/model/ReleasedDataModel.kt
  backend/src/test/kotlin/org/loculus/backend/config/BackendSpringConfigTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataDataUseTermsDisabledEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionControllerClient.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointDataUseTermsDisabledTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointSingleSegmentedTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/GenerateAccessionFromNumberServiceTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/submission/EmptyProcessedDataProviderTest.kt
  backend/src/test/resources/backend_config.json
  backend/src/test/resources/backend_config_data_use_terms_disabled.json
  backend/src/test/resources/backend_config_single_segment.json
  docs/astro.config.mjs
  docs/src/content/docs/for-administrators/data-use-terms.md
  docs/src/content/docs/for-users/submit-sequences.md
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/components/Submission/RevisionForm.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
  website/src/components/Submission/SubmissionForm.tsx
  website/src/config.ts
  website/src/pages/[organism]/search/index.astro
  website/src/pages/[organism]/submission/[groupId]/released.astro
  website/src/pages/[organism]/submission/[groupId]/revise.astro
  website/src/pages/[organism]/submission/[groupId]/submit.astro
  website/src/pages/api-documentation/index.astro
  website/src/types/config.ts
Labels: preview

#3643 add support for NCBI gateway URL
  ingest/Snakefile
  kubernetes/loculus/templates/ingest-config.yaml
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#3646 fix(website): Add special color for organism selector in Loculus color scheme
  website/colors.cjs
Labels: preview

#3644 feat(website): Improve scroll behaviour in search table
  website/src/components/SearchPage/ScrollContainer.tsx
  website/src/components/SearchPage/Table.tsx
  website/src/styles/base.scss
Labels: preview, format_me

#3651 feat(website): Group metadata fields on the revision page
  website/src/components/Edit/DataRow.tsx
  website/src/components/Edit/EditPage.spec.tsx
  website/src/components/Edit/EditPage.tsx
  website/src/pages/[organism]/submission/edit/[accession]/[version].astro
  website/vitest.setup.ts
Labels: preview

#3649 chore(kubernetes): update to LAPIS 0.3.14, SILO 0.5.3
  kubernetes/loculus/values.yaml
Labels: preview

#3640 feat(website): surface reference sequence more clearly on mutations
  integration-tests/tests/specs/features/submission-flow.spec.ts
  website/src/components/SequenceDetailsPage/DataTable.tsx
Labels: preview, format_me

#3667 fix(website): pagination reset on search page table resort
  website/src/components/SearchPage/SearchFullUI.tsx
Labels: preview

#3669 fix(website): Fix scroll issue on browse page split view
  website/src/components/SearchPage/SearchFullUI.tsx
Labels: preview, format_me

#3677 fix(ingest): add back api-key to env variables
  kubernetes/loculus/templates/ingest-deployment.yaml
Labels: preview

#3671 (merging into Anya's PR) Suggestions for data use terms selector
  docs/src/content/docs/for-administrators/data-use-terms.mdx
  website/src/components/DataUseTerms/DataUseTermsSelector.tsx
  website/src/components/Submission/DataUploadForm.tsx
Labels: preview, format_me

#3680 feat(deployment): organism scoped resource specification
  kubernetes/loculus/templates/_resources.tpl
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
Labels: preview

#3588 feat(Helm): Add JSON schema for `values.yaml` validation
  .github/workflows/docs-deploy.yml
  .github/workflows/docs-image.yml
  .github/workflows/docs-test.yml
  .github/workflows/helm-schema-lint.yaml
  docs/.gitignore
  docs/package-lock.json
  docs/package.json
  docs/src/components/MarkdownRenderer.astro
  docs/src/components/SchemaDocs.astro
  docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
  docs/src/content/docs/for-administrators/getting-started.md
  docs/src/content/docs/for-administrators/my-first-loculus.md
  docs/src/content/docs/for-administrators/schema-designs.md
  docs/src/content/docs/for-administrators/setup-with-k3d-and-nginx.mdx
  docs/src/content/docs/for-users/approve-submissions.md
  docs/src/content/docs/for-users/revoke-sequences.md
  docs/src/content/docs/for-users/submit-sequences.md
  docs/src/content/docs/introduction/system-overview.md
  docs/src/content/docs/introduction/what-is-loculus.md
  docs/src/content/docs/reference/helm-chart-config.mdx
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
Labels: preview

#3534 Make pipeline version per Organism
  backend/docs/db/schema.sql
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/service/debug/DeleteSequenceDataService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/CurrentProcessingPipelineTable.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SequenceEntriesTable.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UseNewerProcessingPipelineVersionTask.kt
  backend/src/main/resources/db/migration/V1.10__pipeline_version_per_organism.sql
  backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
  backend/src/test/kotlin/org/loculus/backend/controller/debug/DeleteAllSequenceDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/submission/UseNewerProcessingPipelineVersionTaskTest.kt
  docs/astro.config.mjs
  docs/src/content/docs/for-administrators/build-new-preprocessing-pipeline.md
  docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
  docs/src/content/docs/for-administrators/pipeline-concept.md
  kubernetes/loculus/values.yaml
Labels: preview, update_db_schema

#3686 fix(website): Fix alignment of seq details page
  website/src/components/SearchPage/SeqPreviewModal.tsx
  website/src/components/SequenceDetailsPage/DataTable.tsx
Labels: preview, format_me

#3650 feat(deposition)!: Allow groups to specify which BioProject (and BioSample) we upload their sequences into
  ena-submission/README.md
  ena-submission/flyway/sql/V1.2__alter_project_table_id.sql
  ena-submission/scripts/deposition_dry_run.py
  ena-submission/scripts/get_ena_submission_list.py
  ena-submission/scripts/test_ena_submission.py
  ena-submission/src/ena_deposition/create_assembly.py
  ena-submission/src/ena_deposition/create_project.py
  ena-submission/src/ena_deposition/create_sample.py
  ena-submission/src/ena_deposition/ena_submission_helper.py
  ena-submission/src/ena_deposition/submission_db_helper.py
  ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
  kubernetes/loculus/templates/keycloak-config-map.yaml
  kubernetes/loculus/values.yaml
Labels: preview

#3697 fix!(deployment): update Alignment states and QC metrics header
  kubernetes/loculus/values.yaml
Labels: preview

#3702 Revert "Make pipeline version per Organism"
  backend/docs/db/schema.sql
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/service/debug/DeleteSequenceDataService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/CurrentProcessingPipelineTable.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SequenceEntriesTable.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UseNewerProcessingPipelineVersionTask.kt
  backend/src/main/resources/db/migration/V1.10__pipeline_version_per_organism.sql
  backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
  backend/src/test/kotlin/org/loculus/backend/controller/debug/DeleteAllSequenceDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/service/submission/UseNewerProcessingPipelineVersionTaskTest.kt
  docs/astro.config.mjs
  docs/src/content/docs/for-administrators/build-new-preprocessing-pipeline.md
  docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
  docs/src/content/docs/for-administrators/pipeline-concept.md
  kubernetes/loculus/values.yaml
Labels: preview, update_db_schema

#3704 feat(deployment): improve observability of silo preprocessing errors by force replacing pod in development and exiting the process if failed
  kubernetes/loculus/silo_import_wrapper.sh
  kubernetes/loculus/templates/lapis-silo-deployment.yaml
Labels: preview

#3713 chore(deps): use astro v5 for docs
  docs/package-lock.json
  docs/package.json
Labels: preview

#3681 feat(website): Add button to flag a sequence
  docs/src/content/docs/for-administrators/sequence-reporting.md
  docs/src/content/docs/for-users/report-sequences.md
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.schema.json
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/SeqPreviewModal.tsx
  website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
  website/src/components/SequenceDetailsPage/SequencesDataTableTitle.astro
  website/src/config.ts
  website/src/pages/[organism]/search/index.astro
  website/src/pages/[organism]/submission/[groupId]/released.astro
  website/src/pages/seq/[accessionVersion]/index.astro
  website/src/types/config.ts
Labels: preview

#3703 feat!: Pipeline version per organism (fixed)
  backend/docs/db/schema.sql
  backend/src/main/kotlin/org/loculus/backend/config/BackendSpringConfig.kt
  backend/src/main/kotlin/org/loculus/backend/controller/SubmissionController.kt
  backend/src/main/kotlin/org/loculus/backend/service/debug/DeleteSequenceDataService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/CurrentProcessingPipelineTable.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SequenceEntriesTable.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/UseNewerProcessingPipelineVersionTask.kt
  backend/src/main/resources/db/migration/V1.10__pipeline_version_per_organism.sql
  backend/src/test/kotlin/org/loculus/backend/controller/EndpointTestExtension.kt
  backend/src/test/kotlin/org/loculus/backend/controller/debug/DeleteAllSequenceDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/GetReleasedDataEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt
  backend/src/test/kotlin/org/loculus/backend/service/submission/UseNewerProcessingPipelineVersionTaskTest.kt
  docs/astro.config.mjs
  docs/src/content/docs/for-administrators/build-new-preprocessing-pipeline.md
  docs/src/content/docs/for-administrators/existing-preprocessing-pipelines.md
  docs/src/content/docs/for-administrators/pipeline-concept.md
  kubernetes/loculus/values.yaml
Labels: preview, update_db_schema

#3721 enable flagging on preview
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#3725 chore(deps): SILO v0.5.4
  kubernetes/loculus/values.yaml
Labels: preview

#3730 fix(website)!: use `box-content` for consistent column widths regardless of position
  website/src/components/SearchPage/Table.tsx
Labels: preview

#3700 feat(deposition): add ENA integration tests
  .github/workflows/ena-submission-unit-tests.yaml
  .github/workflows/ena-submission-workflow-tests.yml
  ena-submission/.webinrc
  ena-submission/Dockerfile
  ena-submission/README.md
  ena-submission/scripts/test_ena_submission_integration.py
  ena-submission/src/ena_deposition/create_project.py
  ena-submission/src/ena_deposition/create_sample.py
  ena-submission/src/ena_deposition/ena_submission_helper.py
  ena-submission/src/ena_deposition/submission_db_helper.py
  ena-submission/test/approved_ena_submission_list_test.json
  ena-submission/test/test_config.yaml
  preprocessing/nextclade/tests/test_processing_functions.py
Labels: preview

#3673 feat(deposition): Automate metadata revision of ENA submissions
  .github/workflows/ena-submission-workflow-tests.yml
  ena-submission/ENA_submission.md
  ena-submission/config/defaults.yaml
  ena-submission/scripts/deposition_dry_run.py
  ena-submission/scripts/test_ena_submission.py
  ena-submission/scripts/test_ena_submission_integration.py
  ena-submission/src/ena_deposition/config.py
  ena-submission/src/ena_deposition/create_assembly.py
  ena-submission/src/ena_deposition/create_project.py
  ena-submission/src/ena_deposition/create_sample.py
  ena-submission/src/ena_deposition/ena_submission_helper.py
  ena-submission/src/ena_deposition/ena_types.py
  ena-submission/src/ena_deposition/submission_db_helper.py
  ena-submission/src/ena_deposition/trigger_submission_to_ena.py
  ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
  ena-submission/test/approved_ena_submission_list_test.json
  ena-submission/test/test_revision_submission_request.xml
  ena-submission/test/test_sample_request.xml
  ena-submission/test/text_project_request.xml
Labels: preview

#3735 fix(deployment): add old keycloak flags
  kubernetes/loculus/templates/keycloak-deployment.yaml
Labels: preview

#3757 fix(ingest): format with Snakefile with snakefmt
  ingest/Snakefile
Labels: review please

#3754 feat!(ingest): allows the option to use the ncbi datasets mirror
  ingest/Snakefile
  kubernetes/loculus/templates/ingest-config.yaml
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#3751 feat(website): button to copy download URL
  website/src/components/SearchPage/DownloadDialog/DownloadButton.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
Labels: preview, format_me

#3767 feat(website): Explicitly set `dataFormat=fasta` for sequence downloads
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadUrlGenerator.ts
  website/src/settings.ts
Labels: preview

#3710 feat(website): Add new form to submit individual sequences
  docs/src/content/docs/for-users/submit-sequences.md
  integration-tests/README.md
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/tests/specs/features/submission-flow.spec.ts
  integration-tests/tsconfig.json
  website/src/components/Edit/DataRow.tsx
  website/src/components/Edit/EditPage.spec.tsx
  website/src/components/Edit/EditPage.tsx
  website/src/components/Edit/InputField.tsx
  website/src/components/Edit/InputForm.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/components/Submission/FileUpload/FileUploadComponent.tsx
  website/src/components/Submission/FileUpload/SequenceEntryUploadComponent.tsx
  website/src/components/Submission/FormOrUploadWrapper.spec.tsx
  website/src/components/Submission/FormOrUploadWrapper.tsx
  website/src/components/Submission/RevisionForm.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
  website/src/components/Submission/SubmissionForm.tsx
  website/src/components/Submission/SubmissionPageWrapper.astro
  website/src/pages/[organism]/submission/[groupId]/submit.astro
  website/src/routes/SubmissionRoute.spec.ts
  website/src/routes/SubmissionRoute.ts
  website/src/routes/routes.ts
Labels: preview

#3512 feat!(ingest, prepro): replace fasta filter by a specific metadata filter and add ANY aligned option for segmented organisms
  ingest/Snakefile
  ingest/scripts/filter_sequences.py
  ingest/scripts/metadata_filter.py
  ingest/scripts/parse_nextclade_sort_output.py
  ingest/tests/config_cchf/config.yaml
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  preprocessing/nextclade/src/loculus_preprocessing/config.py
  preprocessing/nextclade/src/loculus_preprocessing/prepro.py
Labels: preview, needs-ppx-values-pr
