Repository loculus-project/loculus, pull requests merged in 2025-09, with the labels that each got.

#4921 feat(website): enable CORS for sequence details and FASTA
  website/src/pages/seq/[accessionVersion]/details.json.ts
  website/src/utils/createDownloadAPIRoute.ts
  website/tests/pages/sequences/accession.fa.spec.ts
Labels: preview, codex

#4939 fix(website): avoid storing default field visibilities
  website/src/components/SearchPage/SearchFullUI.spec.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
Labels: preview, codex

#4833 feat(website): show LAPIS sequence counts on group page
  integration-tests/tests/specs/group/lapis-sequence-count.dependent.spec.ts
  integration-tests/tests/specs/group/management.spec.ts
  website/src/components/User/GroupPage.tsx
  website/src/pages/group/[groupId]/index.astro
Labels: preview, codex

#4862 feat(backend): skip pipeline check when no table updates
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/test/kotlin/org/loculus/backend/service/submission/UseNewerProcessingPipelineVersionTaskTest.kt
Labels: preview, format_me, codex

#4950 docs(extra-files): Clean up tutorial, add more info
  docs/src/content/docs/for-administrators/configuring-extra-files.md
Labels: documentation, preview

#4963 feat(website): refactor restricted use banner to make it easy to modify
  website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
  website/src/components/common/RestrictedUseWarning.tsx
  website/tests/pages/review/index.spec.ts
Labels: preview, format_me

#4773 feat(website): multi pathogen support: sequence details page: only show relevant mutation references
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx
  website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
  website/src/components/SearchPage/SearchForm.spec.tsx
  website/src/components/SearchPage/SearchFullUI.spec.tsx
  website/src/components/SearchPage/fields/MutationField.spec.tsx
  website/src/components/SequenceDetailsPage/DataTable.tsx
  website/src/components/SequenceDetailsPage/RevocationEntryDataTable.astro
  website/src/components/SequenceDetailsPage/SequenceContainer.spec.tsx
  website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
  website/src/components/SequenceDetailsPage/SequencesContainer.tsx
  website/src/components/SequenceDetailsPage/getTableData.spec.ts
  website/src/components/SequenceDetailsPage/getTableData.ts
  website/src/components/Submission/FileUpload/SequenceEntryUploadComponent.tsx
  website/src/components/Submission/FormOrUploadWrapper.spec.tsx
  website/src/components/Submission/FormOrUploadWrapper.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
  website/src/components/common/ActiveFilters.spec.tsx
  website/src/config.ts
  website/src/pages/[organism]/submission/edit/[accession]/[version].astro
  website/src/pages/seq/[accessionVersion]/details.json.ts
  website/src/pages/seq/[accessionVersion]/getSequenceDetailsTableData.ts
  website/src/pages/seq/[accessionVersion]/index.astro
  website/src/types/config.ts
  website/src/types/detailsJson.ts
  website/src/types/referencesGenomes.ts
  website/src/utils/mutation.spec.ts
  website/src/utils/mutation.ts
Labels: preview

#4995 feat(website): multi pathogen: sequence details page: only show relevant sequences
  website/src/components/SequenceDetailsPage/SequenceContainer.spec.tsx
  website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequenceContainer.spec.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequenceViewer.spec.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequenceViewer.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequencesContainer.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/getSequenceNames.spec.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/getSequenceNames.tsx
  website/src/components/SequenceDetailsPage/getTableData.spec.ts
  website/src/services/serviceHooks.ts
  website/src/utils/sequenceTypeHelpers.ts
  website/vitest.setup.ts
Labels: preview

#5035 test(integration-tests): cover navigation flow against main
  integration-tests/tests/specs/features/navigation.spec.ts
  website/tests/e2e.fixture.ts
  website/tests/pages/navigation.fixture.ts
  website/tests/pages/navigation.spec.ts
Labels: codex

#5034 test(integration-tests): move landing page e2e to integration tests
  integration-tests/tests/specs/features/landing-page.spec.ts
  website/tests/pages/index.spec.ts
Labels: codex

#5040 test(integration-tests): add metadata template coverage
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/tests/specs/features/metadata-template.spec.ts
  website/tests/pages/submission/template.spec.ts
Labels: codex

#5044 fix(docs): fix link
  docs/src/content/docs/for-users/submit-extra-files.md
Labels: preview

#5049 test(integration-tests): verify backend rejects invalid tokens
  integration-tests/tests/specs/backend/authentication.spec.ts
  website/tests/backendAuth.spec.ts
Labels: codex

#5048 refactor(website): migrate useQueryAsState.js to TS
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/Table.tsx
  website/src/components/SearchPage/fields/DateRangeField.tsx
  website/src/components/SearchPage/useQueryAsState.js
  website/src/components/SearchPage/useQueryAsState.spec.ts
  website/src/components/SearchPage/useQueryAsState.ts
  website/src/hooks/useUrlParamState.ts
  website/src/pages/[organism]/submission/[groupId]/released.astro
  website/src/types/config.ts
  website/src/types/lapis.ts
  website/src/utils/extractFieldValue.ts
  website/src/utils/parseUrlSearchParams.ts
  website/src/utils/search.ts
  website/src/utils/serversideSearch.ts
Labels: preview

#5055 refactor(website): don't duplicate the state in useUrlParamState
  website/src/hooks/useUrlParamState.ts
Labels: preview

#4996 feat!(config): use new cchf dataset
  ingest/Snakefile
  ingest/config/defaults.yaml
  kubernetes/loculus/values.yaml
Labels: preview

#5073 fix(website): improve seqset citation formats on export
  website/src/components/SeqSetCitations/ExportSeqSet.tsx
  website/src/components/SeqSetCitations/SeqSetItemActions.tsx
  website/src/pages/seqsets/[seqSetId].[version].astro
Labels: preview, codex

#5094 chore(deps): bump SILO to use backported health-check in version 0.7.10.2
  kubernetes/loculus/values.yaml
Labels: preview

#5093 feat(deployment): Add liveness probe to silo-deployment.yaml
  kubernetes/loculus/templates/silo-deployment.yaml
Labels: preview

#5115 chore(website/deps): rename deprecated tanstack query isLoading -> isPending, make axios changes for upgrade
  website/package-lock.json
  website/package.json
  website/src/components/DataUseTerms/EditDataUseTermsModal.tsx
  website/src/components/Edit/EditPage.tsx
  website/src/components/SearchPage/SearchFullUI.spec.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/fields/AutoCompleteOptions.ts
  website/src/components/SearchPage/fields/LineageField.spec.tsx
  website/src/components/SearchPage/fields/MultiChoiceAutoCompleteField.spec.tsx
  website/src/components/SearchPage/fields/MultiChoiceAutoCompleteField.tsx
  website/src/components/SearchPage/fields/SingleChoiceAutoCompleteField.spec.tsx
  website/src/components/SearchPage/fields/SingleChoiceAutoCompleteField.tsx
  website/src/components/SeqSetCitations/SeqSetForm.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/services/backendClient.ts
Labels: review please

#5028 feat(website): multi pathogen feature branch
  kubernetes/loculus/values.schema.json
  kubernetes/loculus/values.yaml
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.spec.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadDialog.tsx
  website/src/components/SearchPage/DownloadDialog/DownloadForm.tsx
  website/src/components/SearchPage/DownloadDialog/OptionBlock.tsx
  website/src/components/SearchPage/DownloadDialog/SequenceFilters.tsx
  website/src/components/SearchPage/SearchForm.spec.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/SearchFullUI.spec.tsx
  website/src/components/SearchPage/SearchFullUI.tsx
  website/src/components/SearchPage/SuborganismSelector.spec.tsx
  website/src/components/SearchPage/SuborganismSelector.tsx
  website/src/components/SearchPage/fields/MutationField.spec.tsx
  website/src/components/SearchPage/stillRequiresSuborganismSelection.tsx
  website/src/components/SequenceDetailsPage/DataTable.tsx
  website/src/components/SequenceDetailsPage/MutationBadge.tsx
  website/src/components/SequenceDetailsPage/RevocationEntryDataTable.astro
  website/src/components/SequenceDetailsPage/SequenceContainer.spec.tsx
  website/src/components/SequenceDetailsPage/SequenceDataUI.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequenceContainer.spec.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequenceViewer.spec.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequenceViewer.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/SequencesContainer.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/getSequenceNames.spec.tsx
  website/src/components/SequenceDetailsPage/SequencesDisplay/getSequenceNames.tsx
  website/src/components/SequenceDetailsPage/getTableData.spec.ts
  website/src/components/SequenceDetailsPage/getTableData.ts
  website/src/components/Submission/FileUpload/SequenceEntryUploadComponent.tsx
  website/src/components/Submission/FormOrUploadWrapper.spec.tsx
  website/src/components/Submission/FormOrUploadWrapper.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
  website/src/components/common/ActiveFilters.spec.tsx
  website/src/config.ts
  website/src/pages/[organism]/submission/edit/[accession]/[version].astro
  website/src/pages/seq/[accessionVersion]/details.json.ts
  website/src/pages/seq/[accessionVersion]/getSequenceDetailsTableData.ts
  website/src/pages/seq/[accessionVersion]/index.astro
  website/src/services/serviceHooks.ts
  website/src/types/config.ts
  website/src/types/detailsJson.ts
  website/src/types/lapis.ts
  website/src/types/referencesGenomes.ts
  website/src/utils/mutation.spec.ts
  website/src/utils/mutation.ts
  website/src/utils/search.ts
  website/src/utils/sequenceTypeHelpers.ts
  website/vitest.setup.ts
Labels: preview
