Repository loculus-project/loculus, pull requests merged in 2025-06, with the labels that each got.

#4262 fix(k8s): give backend and LAPIS 3min to become live with startup probe
  kubernetes/loculus/templates/lapis-deployment.yaml
  kubernetes/loculus/templates/loculus-backend.yaml
  kubernetes/loculus/values_preview_server.yaml
Labels: preview

#4274 fix(website): fallback to `name` if `displayName` not available
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.tsx
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/SearchPage/fields/NormalTextField.tsx
Labels: preview

#4252 fix(backend): fix large seqset bug
  backend/src/main/kotlin/org/loculus/backend/service/seqsetcitations/SeqSetCitationsDatabaseService.kt
Labels: preview

#4304 feat(integration-tests): add group management tests
  integration-tests/tests/pages/group.page.ts
  integration-tests/tests/specs/group/management.spec.ts
  website/tests/pages/user/group/group.page.ts
  website/tests/pages/user/group/index.spec.ts
Labels: codex

#4313 style(website): de-emphasize seqset author display
  website/src/components/SeqSetCitations/AuthorDetails.tsx
Labels: codex

#4307 feat(website): improve seqset add button
  website/src/components/SeqSetCitations/SeqSetListActions.tsx
  website/src/pages/seqsets/index.astro
Labels: codex

#4325 fix(website): improve seqset details layout on mobile
  website/src/pages/seqsets/[seqSetId].[version].astro
Labels: preview, codex

#4227 feat(backend): validate file existence and fetch file size
  backend/docs/db/schema.sql
  backend/src/main/kotlin/org/loculus/backend/api/SubmissionTypes.kt
  backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt
  backend/src/main/kotlin/org/loculus/backend/service/files/FilesDatabaseService.kt
  backend/src/main/kotlin/org/loculus/backend/service/files/FilesTable.kt
  backend/src/main/kotlin/org/loculus/backend/service/files/S3Service.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/FileMappingPreconditionValidator.kt
  backend/src/main/kotlin/org/loculus/backend/service/submission/SubmissionDatabaseService.kt
  backend/src/main/resources/db/migration/V1.13__file_sharing_add_size.sql
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ReviseEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmissionConvenienceClient.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEditedSequenceEntryVersionEndpointTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointFileSharingTest.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitProcessedDataEndpointTest.kt
Labels: preview, update_db_schema

#4322 fix(backend): prevent open sequence being set to Open
  backend/src/main/kotlin/org/loculus/backend/service/datauseterms/DataUseTermsPreconditionValidator.kt
  backend/src/test/kotlin/org/loculus/backend/controller/datauseterms/DataUseTermsControllerTest.kt
Labels: format_me

#4310 fix(backend): reject empty FASTA segments
  backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt
  backend/src/main/kotlin/org/loculus/backend/utils/FastaReader.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/SubmitEndpointTest.kt
  docs/src/content/docs/reference/fasta-format.md
Labels: preview

#4312 fix(website): prevent text selection from triggering row click
  website/src/components/SearchPage/Table.tsx
Labels: preview, format_me, codex

#4297 Update get ena submission list cronjob to only submit the most recent version if multiple versions are available
  ena-submission/scripts/get_ena_submission_list.py
  ena-submission/scripts/test_ena_submission_integration.py
  ena-submission/src/ena_deposition/create_assembly.py
  ena-submission/src/ena_deposition/create_project.py
  ena-submission/src/ena_deposition/create_sample.py
  ena-submission/src/ena_deposition/submission_db_helper.py
  ena-submission/src/ena_deposition/upload_external_metadata_to_loculus.py
Labels: preview

#4354 ci(integration-tests): run different browser tests in different containers
  .github/workflows/integration-tests.yml
  integration-tests/playwright.config.ts
Labels: codex

#4372 fix(kubernetes): remove redundant and wrong keycloak URL template
  kubernetes/loculus/templates/_keycloak-url.tpl
Labels: preview

#4177 feat(ingest): refactor call_loculus and compare_hashes
  ingest/Snakefile
  ingest/scripts/call_loculus.py
  ingest/scripts/compare_hashes.py
  ingest/scripts/prepare_metadata.py
  ingest/tests/expected_output_cchf/metadata_post_prepare.ndjson
  ingest/tests/expected_output_cchf/unchanged.json
  ingest/tests/test_data_cchf/ncbi_dataset/data/data_report.jsonl
  ingest/tests/test_data_cchf/previous_submissions.json
  ingest/tests/test_data_cchf/previous_submissions.ndjson
  ingest/tests/test_data_cchf/sequences.fasta
  kubernetes/loculus/values.yaml
Labels: preview

#4253 fix(website): move download button to file upload component on edit page
  website/src/components/Edit/EditPage.tsx
  website/src/components/Edit/SequencesForm.tsx
  website/src/components/Submission/FileUpload/FileUploadComponent.tsx
Labels: preview

#4379 fix(backend): file upload for revisions
  backend/src/main/kotlin/org/loculus/backend/model/SubmitModel.kt
  backend/src/test/kotlin/org/loculus/backend/controller/submission/ReviseEndpointTest.kt
Labels: preview

#4391 feat(deployment): Add `submissionId`, `groupName` to default metadata downloads
  integration-tests/tests/specs/features/search/download.dependent.spec.ts
  kubernetes/loculus/templates/_common-metadata.tpl
Labels: preview

#4356 feat(website): add dynamic banner message
  kubernetes/loculus/templates/_common-metadata.tpl
  kubernetes/loculus/values.schema.json
  website/src/layouts/BaseLayout.astro
  website/src/services/bannerMessageService.ts
  website/src/types/config.ts
Labels: preview, format_me, codex

#4331 fix(website): display authors as "FirstName LastName" in topmatter
  website/src/components/SequenceDetailsPage/AuthorList.tsx
  website/src/components/SequenceDetailsPage/getDataTableData.spec.ts
  website/src/components/SequenceDetailsPage/getDataTableData.ts
Labels: discussion, preview, codex

#4445 chore(ci): allow triggering arm-builds with PR label
  .github/workflows/build-arm-images.yaml
Labels: arm-images

#4298 feat(website): Add dialog to view processed files in 'review' window (before approving)
  integration-tests/tests/pages/review.page.ts
  integration-tests/tests/specs/features/file-sharing.spec.ts
  kubernetes/loculus/templates/_common-metadata.tpl
  website/src/components/ReviewPage/FilesDialog.tsx
  website/src/components/ReviewPage/ReviewCard.tsx
  website/src/components/ReviewPage/ReviewPage.spec.tsx
  website/src/components/ReviewPage/ReviewPage.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/components/Submission/FileUpload/FolderUploadComponent.tsx
  website/src/config.ts
  website/src/pages/[organism]/submission/[groupId]/review.astro
  website/src/pages/seq/[accessionVersion]/[fileCategory]/[fileName].ts
  website/src/types/backend.ts
  website/src/types/config.ts
  website/vitest.setup.ts
Labels: preview

#4477 fix(website): make rsuite date picker work acceptably with keyboard control
  website/package-lock.json
  website/package.json
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/SearchPage/fields/DateRangeField.spec.tsx
Labels: website, preview

#4480 feat(website): switch date format in date picker fields from dd/MM/yyyy to yyyy-MM-dd
  integration-tests/tests/specs/features/search/active-filters.dependent.spec.ts
  website/src/components/SearchPage/fields/DateField.spec.tsx
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/SearchPage/fields/DateRangeField.spec.tsx
Labels: preview

#4462 feat(website): Add tooltips to single submission
  integration-tests/tests/pages/submission.page.ts
  website/src/components/Edit/DataRow.tsx
  website/src/components/Edit/EditPage.spec.tsx
  website/src/components/Edit/MetadataForm.tsx
  website/src/components/Submission/FileUpload/ColumnMappingModal.tsx
  website/src/components/Submission/FormOrUploadWrapper.spec.tsx
  website/src/components/Submission/InputFieldTooltip.tsx
  website/src/components/Submission/SubmissionForm.spec.tsx
Labels: preview

#4520 fix(website): deflake tests by disabling buttons until react has hydrated and increasing timeout
  .gitignore
  integration-tests/tests/fixtures/auth.fixture.ts
  integration-tests/tests/fixtures/sequence.fixture.ts
  integration-tests/tests/pages/review.page.ts
  integration-tests/tests/readonly.setup.ts
  integration-tests/tests/specs/features/submission-flow.spec.ts
  website/src/components/Edit/InputField.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/fields/MutationField.tsx
Labels: preview

#4532 feat(website): componentize disabling elements until hydration
  website/src/components/DisabledUntilHydrated.tsx
  website/src/components/Edit/InputField.tsx
  website/src/components/Group/GroupForm.tsx
  website/src/components/SearchPage/SearchForm.tsx
  website/src/components/SearchPage/fields/AutoCompleteField.tsx
  website/src/components/SearchPage/fields/DateField.tsx
  website/src/components/SearchPage/fields/MutationField.tsx
  website/src/components/SearchPage/fields/NormalTextField.tsx
  website/src/components/SeqSetCitations/SeqSetItemActions.tsx
  website/src/components/Submission/DataUploadForm.tsx
  website/src/components/User/GroupPage.tsx
Labels: preview, codex

#4539 feat(website): add show more for long values
  website/src/components/SequenceDetailsPage/DataTableEntryValue.tsx
Labels: preview, codex

#4554 fix(ci): Bump setup Node action in format website
  .github/workflows/format-website-on-dispatch.yml
Labels: format_me

#4531 chore(backend): fix Kotlin and Gradle warnings, bump gradle to 8.14.0
  backend/build.gradle
  backend/gradle.properties
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
Labels: preview, review please
